In [189]:
# Librerias

import pandas as pd

In [190]:
archivo = 'files/raw/datos_limpios.xlsx'
#cargamos cada dato por separado
df_julio = pd.read_excel(archivo, sheet_name='Plantilla a Julio 2019')
df_bajas = pd.read_excel(archivo, sheet_name='Bajas de Agosto 2019')
df_altas = pd.read_excel(archivo, sheet_name='Altas de Agosto 2019')

# ARCHIVO DF_JULIO

1) analizamos df_julio
viene todos lso datos de julio

In [191]:
df_julio.head()

,Convenio Aplicable,Localización País,Área Funcional,Localización Ciudad,Subactividad_desc,Año,COD. UNIDAD DE NEGOCIO,Mes,Reducción de Jormada,Tipo de contrato,...,HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO,Nombre del puesto,Nacionalidad,Estado de empleado,PROMEDIO DE HORAS SEMANALES TRABAJADAS EN EL MES,Fecha de Nacimiento,Clase de empleado,Discapacidad,Fecha de Alta,ID persona
0,Sí,España,Red - Planificación Tecnológica,VIZCAYA,tecnologíayplanificación,2019,156,Jul,No,Fijo,...,37.5,ENCARGADO DE OPERACION,ESPAÑOLA,Activo,37.5,1954-09-08,EMP,No,1978-12-21,Persona 1716852
1,Sí,España,Red - Planificación Tecnológica,ALICANTE,tecnologíayplanificación,2019,156,Jul,No,Fijo,...,37.5,TITULADO SUPERIOR O MASTER,ESPAÑOLA,Activo,37.5,1952-02-12,EMP,No,1979-07-13,Persona 1716853
2,No,España,Direccion,TARRAGONA,gestionydireccion,2019,156,Jul,No,Fijo,...,37.5,TITULADO SUPERIOR O MASTER,ESPAÑOLA,Activo,37.5,1954-06-07,EMP,No,1981-12-01,Persona 1716854
3,Sí,España,Red - Planificación Tecnológica,HUESCA,tecnologíayplanificación,2019,156,Jul,No,Fijo,...,37.5,OPERADOR DE COMUNICACIONES,ESPAÑOLA,Activo,37.5,1956-06-04,EMP,No,1981-12-01,Persona 1716855
4,Sí,España,Direccion,MADRID,gestionydireccion,2019,156,Jul,No,Fijo,...,37.5,TITULADO SUPERIOR O MASTER,ESPAÑOLA,Activo,37.5,1966-12-01,EMP,No,1986-12-15,Persona 1716856

In [192]:
df_julio.info()

<class 'pandas.DataFrame'>
RangeIndex: 48431 entries, 0 to 48430
Data columns (total 24 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Convenio Aplicable                                 23800 non-null  str
 1   Localización País                                  48431 non-null  str
 2   Área Funcional                                     15995 non-null  str
 3   Localización Ciudad                                48431 non-null  str
 4   Subactividad_desc                                  48431 non-null  str
 5   Año                                                48431 non-null  int64
 6   COD. UNIDAD DE NEGOCIO                             48431 non-null  int64
 7   Mes                                                48431 non-null  str
 8   Reducción de Jormada                               48431 non-null  str
 9   Tipo de contrato                                   48431 non-null  str
 10  División                                           48431 non-null  str
 11  Subactividad                                       48431 non-null  str
 12  Género                                             48431 non-null  str
 13  Departamento                                       47986 non-null  str
 14  HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO     48431 non-null  float64
 15  Nombre del puesto                                  48431 non-null  str
 16  Nacionalidad                                       16019 non-null  str
 17  Estado de empleado                                 48431 non-null  str
 18  PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES  48431 non-null  float64
 19  Fecha de Nacimiento                                48431 non-null  datetime64[us]
 20  Clase de empleado                                  48431 non-null  str
 21  Discapacidad                                       48431 non-null  str
 22  Fecha de Alta                                      48431 non-null  datetime64[us]
 23  ID persona                                         48431 non-null  str
dtypes: datetime64[us](2), float64(2), int64(2), str(18)
memory usage: 8.9 MB

In [193]:
#comenzamos columna a columna

0) Convenio Aplicable

In [194]:
df_julio['Convenio Aplicable'].unique()

<StringArray>
['Sí', 'No', nan]
Length: 3, dtype: str

In [195]:
# Conteo absoluto (número de filas)
conteo = df_julio['Convenio Aplicable'].value_counts(dropna=False)

# Conteo en porcentaje
porcentaje = df_julio['Convenio Aplicable'].value_counts(normalize=True, dropna=False) * 100

# Unimos ambos resultados en una tabla clara
resultado = pd.DataFrame({'Cantidad': conteo, 'Porcentaje (%)': porcentaje})
print(resultado)

                    Cantidad  Porcentaje (%)
Convenio Aplicable
NaN                    24631       50.857922
Sí                     13270       27.399806
No                     10530       21.742273

In [196]:
# ojo el 50% de los datos de esta categoria son nulos

1) Localizacion  Pais

In [197]:
df_julio['Localización País']

0        España
1        España
2        España
3        España
4        España
5        España
6        España
7        España
8        España
9        España
10       España
11       España
12       España
13       España
14       España
15       España
16       España
17       España
18       España
19       España
20       España
21       España
22       España
23       España
24       España
25       España
26       España
27       España
28       España
29       España
30       España
31       España
32       España
33       España
34       España
35       España
36       España
37       España
38       España
39       España
40       España
41       España
42       España
43       España
44       España
45       España
46       España
47       España
48       España
49       España
50       España
51       España
52       España
53       España
54       España
55       España
56       España
57       España
58       España
59       España
60       España
61       España
62       España
63       España
64       España
65       España
66       España
67       España
68       España
69       España
70       España
71       España
72       España
73       España
74       España
75       España
76       España
77       España
78       España
79       España
80       España
81       España
82       España
83       España
84       España
85       España
86       España
87       España
88       España
89       España
90       España
91       España
92       España
93       España
94       España
95       España
96       España
97       España
98       España
99       España
100      España
101      España
102      España
103      España
104      España
105      España
106      España
107      España
108      España
109      España
110      España
111      España
112      España
113      España
114      España
115      España
116      España
117      España
118      España
119      España
120      España
121      España
122      España
123      España
124      España
125      España
126      España
127      España
128      España
129      España
130      España
131      España
132      España
133      España
134      España
135      España
136      España
137      España
138      España
139      España
140      España
141      España
142      España
143      España
144      España
145      España
146      España
147      España
148      España
149      España
150      España
151      España
152      España
153      España
154      España
155      España
156      España
157      España
158      España
159      España
160      España
161      España
162      España
163      España
164      España
165      España
166      España
167      España
168      España
169      España
170      España
171      España
172      España
173      España
174      España
175      España
176      España
177      España
178      España
179      España
180      España
181      España
182      España
183      España
184      España
185      España
186      España
187      España
188      España
189      España
190      España
191      España
192      España
193      España
194      España
195      España
196      España
197      España
198      España
199      España
200      España
201      España
202      España
203      España
204      España
205      España
206      España
207      España
208      España
209      España
210      España
211      España
212      España
213      España
214      España
215      España
216      España
217      España
218      España
219      España
220      España
221      España
222      España
223      España
224      España
225      España
226      España
227      España
228      España
229      España
230      España
231      España
232      España
233      España
234      España
235      España
236      España
237      España
238      España
239      España
240      España
241      España
242      España
243      España
244      España
245      España
246      España
247      España
248      España
249      España
250      España
251      España
252      España
253      España
254      España
255      España
256      España
257      España
258      España
259      España
260      España
261      España
262      España
263      España
264      España
265      España
266      España
267      España
268      España
269      España
270      España
271      España
272      España
273      España
274      España
275      España
276      España
277      España
278      España
279      España
280      España
281      España
282      España
283      España
284      España
285      España
286      España
287      España
288      España
289      España
290      España
291      España
292      España
293      España
294      España
295      España
296      España
297      España
298      España
299      España
300      España
301      España
302      España
303      España
304      España
305      España
306      España
307      España
308      España
309      España
310      España
311      España
312      España
313      España
314      España
315      España
316      España
317      España
318      España
319      España
320      España
321      España
322      España
323      España
324      España
325      España
326      España
327      España
328      España
329      España
330      España
331      España
332      España
333      España
334      España
335      España
336      España
337      España
338      España
339      España
340      España
341      España
342      España
343      España
344      España
345      España
346      España
347      España
348      España
349      España
350      España
351      España
352      España
353      España
354      España
355      España
356      España
357      España
358      España
359      España
360      España
361      España
362      España
363      España
364      España
365      España
366      España
367      España
368      España
369      España
370      España
371      España
372      España
373      España
374      España
375      España
376      España
377      España
378      España
379      España
380      España
381      España
382      España
383      España
384      España
385      España
386      España
387      España
388      España
389      España
390      España
391      España
392      España
393      España
394      España
395      España
396      España
397      España
398      España
399      España
400      España
401      España
402      España
403      España
404      España
405      España
406      España
407      España
408      España
409      España
410      España
411      España
412      España
413      España
414      España
415      España
416      España
417      España
418      España
419      España
420      España
421      España
422      España
423      España
424      España
425      España
426      España
427      España
428      España
429      España
430      España
431      España
432      España
433      España
434      España
435      España
436      España
437      España
438      España
439      España
440      España
441      España
442      España
443      España
444      España
445      España
446      España
447      España
448      España
449      España
450      España
451      España
452      España
453      España
454      España
455      España
456      España
457      España
458      España
459      España
460      España
461      España
462      España
463      España
464      España
465      España
466      España
467      España
468      España
469      España
470      España
471      España
472      España
473      España
474      España
475      España
476      España
477      España
478      España
479      España
480      España
481      España
482      España
483      España
484      España
485      España
486      España
487      España
488      España
489      España
490      España
491      España
492      España
493      España
494      España
495      España
496      España
497      España
498      España
499      España
500      España
501      España
502      España
503      España
504      España
505      España
506      España
507      España
508      España
509      España
510      España
511      España
512      España
513      España
514      España
515      España
516      España
517      España
518      España
519      España
520      España
521      España
522      España
523      España
524      España
525      España
526      España
527      España
528      España
529      España
530      España
531      España
532      España
533      España
534      España
535      España
536      España
537      España
538      España
539      España
540      España
541      España
542      España
543      España
544      España
545      España
546      España
547      España
548      España
549      España
550      España
551      España
552      España
553      España
554      España
555      España
556      España
557      España
558      España
559      España
560      España
561      España
562      España
563      España
564      España
565      España
566      España
567      España
568      España
569      España
570      España
571      España
572      España
573      España
574      España
575      España
576      España
577      España
578      España
579      España
580      España
581      España
582      España
583      España
584      España
585      España
586      España
587      España
588      España
589      España
590      España
591      España
592      España
593      España
594      España
595      España
596      España
597      España
598      España
599      España
600      España
601      España
602      España
603      España
604      España
605      España
606      España
607      España
608      España
609      España
610      España
611      España
612      España
613      España
614      España
615      España
616      España
617      España
618      España
619      España
620      España
621      España
622      España
623      España
624      España
625      España
626      España
627      España
628      España
629      España
630      España
631      España
632      España
633      España
634      España
635      España
636      España
637      España
638      España
639      España
640      España
641      España
642      España
643      España
644      España
645      España
646      España
647      España
648      España
649      España
650      España
651      España
652      España
653      España
654      España
655      España
656      España
657      España
658      España
659      España
660      España
661      España
662      España
663      España
664      España
665      España
666      España
667      España
668      España
669      España
670      España
671      España
672      España
673      España
674      España
675      España
676      España
677      España
678      España
679      España
680      España
681      España
682      España
683      España
684      España
685      España
686      España
687      España
688      España
689      España
690      España
691      España
692      España
693      España
694      España
695      España
696      España
697      España
698      España
699      España
700      España
701      España
702      España
703      España
704      España
705      España
706      España
707      España
708      España
709      España
710      España
711      España
712      España
713      España
714      España
715      España
716      España
717      España
718      España
719      España
720      España
721      España
722      España
723      España
724      España
725      España
726      España
727      España
728      España
729      España
730      España
731      España
732      España
733      España
734      España
735      España
736      España
737      España
738      España
739      España
740      España
741      España
742      España
743      España
744      España
745      España
746      España
747      España
748      España
749      España
750      España
751      España
752      España
753      España
754      España
755      España
756      España
757      España
758      España
759      España
760      España
761      España
762      España
763      España
764      España
765      España
766      España
767      España
768      España
769      España
770      España
771      España
772      España
773      España
774      España
775      España
776      España
777      España
778      España
779      España
780      España
781      España
782      España
783      España
784      España
785      España
786      España
787      España
788      España
789      España
790      España
791      España
792      España
793      España
794      España
795      España
796      España
797      España
798      España
799      España
800      España
801      España
802      España
803      España
804      España
805      España
806      España
807      España
808      España
809      España
810      España
811      España
812      España
813      España
814      España
815      España
816      España
817      España
818      España
819      España
820      España
821      España
822      España
823      España
824      España
825      España
826      España
827      España
828      España
829      España
830      España
831      España
832      España
833      España
834      España
835      España
836      España
837      España
838      España
839      España
840      España
841      España
842      España
843      España
844      España
845      España
846      España
847      España
848      España
849      España
850      España
851      España
852      España
853      España
854      España
855      España
856      España
857      España
858      España
859      España
860      España
861      España
862      España
863      España
864      España
865      España
866      España
867      España
868      España
869      España
870      España
871      España
872      España
873      España
874      España
875      España
876      España
877      España
878      España
879      España
880      España
881      España
882      España
883      España
884      España
885      España
886      España
887      España
888      España
889      España
890      España
891      España
892      España
893      España
894      España
895      España
896      España
897      España
898      España
899      España
900      España
901      España
902      España
903      España
904      España
905      España
906      España
907      España
908      España
909      España
910      España
911      España
912      España
913      España
914      España
915      España
916      España
917      España
918      España
919      España
920      España
921      España
922      España
923      España
924      España
925      España
926      España
927      España
928      España
929      España
930      España
931      España
932      España
933      España
934      España
935      España
936      España
937      España
938      España
939      España
940      España
941      España
942      España
943      España
944      España
945      España
946      España
947      España
948      España
949      España
950      España
951      España
952      España
953      España
954      España
955      España
956      España
957      España
958      España
959      España
960      España
961      España
962      España
963      España
964      España
965      España
966      España
967      España
968      España
969      España
970      España
971      España
972      España
973      España
974      España
975      España
976      España
977      España
978      España
979      España
980      España
981      España
982      España
983      España
984      España
985      España
986      España
987      España
988      España
989      España
990      España
991      España
992      España
993      España
994      España
995      España
996      España
997      España
998      España
999      España
1000     España
1001     España
1002     España
1003     España
1004     España
1005     España
1006     España
1007     España
1008     España
1009     España
1010     España
1011     España
1012     España
1013     España
1014     España
1015     España
1016     España
1017     España
1018     España
1019     España
1020     España
1021     España
1022     España
1023     España
1024     España
1025     España
1026     España
1027     España
1028     España
1029     España
1030     España
1031     España
1032     España
1033     España
1034     España
1035     España
1036     España
1037     España
1038     España
1039     España
1040     España
1041     España
1042     España
1043     España
1044     España
1045     España
1046     España
1047     España
1048     España
1049     España
1050     España
1051     España
1052     España
1053     España
1054     España
1055     España
1056     España
1057     España
1058     España
1059     España
1060     España
1061     España
1062     España
1063     España
1064     España
1065     España
1066     España
1067     España
1068     España
1069     España
1070     España
1071     España
1072     España
1073     España
1074     España
1075     España
1076     España
1077     España
1078     España
1079     España
1080     España
1081     España
1082     España
1083     España
1084     España
1085     España
1086     España
1087     España
1088     España
1089     España
1090     España
1091     España
1092     España
1093     España
1094     España
1095     España
1096     España
1097     España
1098     España
1099     España
1100     España
1101     España
1102     España
1103     España
1104     España
1105     España
1106     España
1107     España
1108     España
1109     España
1110     España
1111     España
1112     España
1113     España
1114     España
1115     España
1116     España
1117     España
1118     España
1119     España
1120     España
1121     España
1122     España
1123     España
1124     España
1125     España
1126     España
1127     España
1128     España
1129     España
1130     España
1131     España
1132     España
1133     España
1134     España
1135     España
1136     España
1137     España
1138     España
1139     España
1140     España
1141     España
1142     España
1143     España
1144     España
1145     España
1146     España
1147     España
1148     España
1149     España
1150     España
1151     España
1152     España
1153     España
1154     España
1155     España
1156     España
1157     España
1158     España
1159     España
1160     España
1161     España
1162     España
1163     España
1164     España
1165     España
1166     España
1167     España
1168     España
1169     España
1170     España
1171     España
1172     España
1173     España
1174     España
1175     España
1176     España
1177     España
1178     España
1179     España
1180     España
1181     España
1182     España
1183     España
1184     España
1185     España
1186     España
1187     España
1188     España
1189     España
1190     España
1191     España
1192     España
1193     España
1194     España
1195     España
1196     España
1197     España
1198     España
1199     España
1200     España
1201     España
1202     España
1203     España
1204     España
1205     España
1206     España
1207     España
1208     España
1209     España
1210     España
1211     España
1212     España
1213     España
1214     España
1215     España
1216     España
1217     España
1218     España
1219     España
1220     España
1221     España
1222     España
1223     España
1224     España
1225     España
1226     España
1227     España
1228     España
1229     España
1230     España
1231     España
1232     España
1233     España
1234     España
1235     España
1236     España
1237     España
1238     España
1239     España
1240     España
1241     España
1242     España
1243     España
1244     España
1245     España
1246     España
1247     España
1248     España
1249     España

In [198]:
df_julio['Localización País'].unique()

<StringArray>
['España', 'Brasil']
Length: 2, dtype: str

In [199]:
# Conteo absoluto por país
conteo_pais = df_julio['Localización País'].value_counts(dropna=False)

# Conteo en porcentaje
porcentaje_pais = df_julio['Localización País'].value_counts(normalize=True, dropna=False) * 100

# Unimos los resultados en una tabla clara
resultado_pais = pd.DataFrame({'Cantidad': conteo_pais, 'Porcentaje (%)': porcentaje_pais})
print(resultado_pais)

                   Cantidad  Porcentaje (%)
Localización País
Brasil                32412       66.924078
España                16019       33.075922

2) Area Funcional

In [200]:
df_julio['Área Funcional'].unique()

<StringArray>
[                          'Red - Planificación Tecnológica',
                                                 'Direccion',
            'Seguridad y Prot. - Continuidad de operaciones',
                      'Seguridad y Prot. - Seguridad Física',
           'Seguridad y Prot. - Generalista/Multidisciplina',
                   'Finanzas, Adm. y CDG - (sin clasificar)',
                               'RRHH - Talento y Desarrollo',
                       'Red - Control de Operaciones de Red',
             'Red - Inst. y Manten. Red de Acceso y Troncal',
        'Op. Comerciales - Soporte de Operaciones de Ventas',
        'Op. Comerciales - Adm. Comercial y Liq. Comisiones',
    'B2C Ventas - Gestión Canales Comerciales (Dir. e Ind.)',
             'B2B Empresas y Pymes - Backoffice de Atención',
                     'B2C Ventas - Gestión Canal Telefónico',
                      'B2C Atención al Cliente - Backoffice',
                     'B2B Empresas y Pymes (sin clasificar)',
                                'Negocio Mayorista - Ventas',
           'B2B Empresas y Pymes - Preventa Grandes Cuentas',
                      'B2C Ventas - Planificación Comercial',
                                'TI - Estrategia y Gobierno',
                          'RRHH - Selección y Reclutamiento',
             'Servicios Generales - Prestación de servicios',
                        'Asesoría Jurídica (sin clasificar)',
                  'RRHH - Relaciones Laborales y Sindicales',
                                           'TI - Producción',
               'B2B Empresas y Pymes - Preventa Generalista',
           'Finanzas, Adm. y CDG - Planificación Financiera',
                          'RRHH - Planificación y Reporting',
        'Finanzas, Adm. y CDG - Generalista/Multidisciplina',
                   'Negocio Mayorista - Gestión de Clientes',
            'B2B Empresas y Pymes - Planificación Comercial',
 'Finanzas, Adm. y CDG - Planificación y Control de Gestión',
                                        'B2C Marketing - BI',
                'B2C Marketing - Planificación de Marketing',
                              'TI - Aplicaciones/Desarrollo',
                         'B2B Empresas y Pymes - Ventas B2B',
                                       'RRHH - Organización',
               'Red - Ingeniería de Red de Acceso y Troncal',
                     'B2C Marketing - Marketing de Producto',
                          'B2B Empresas y Pymes - Marketing',
                            'B2C Marketing (sin clasificar)',
                       'Media - Generalista/Multidisciplina',
                     'B2C Marketing - Marketing de Clientes',
           'Negocio Mayorista - Generalista/Multidisciplina',
        'B2C Marketing - Publicidad, Comunicación y Eventos',
                       'Dentro de Convenio (sin clasificar)',
                                'B2C Marketing - Terminales',
                'Op. Comerciales - Logística y Distribucion',
                      'Auditoría y Control Int. - Auditoría',
    'Auditoría y Control Int. - Intervención y Control Int.',
        'Servicios Generales - Inmobiliario e instalaciones',
                                     'RRHH (sin clasificar)',
                  'Estrategia - Generalista/Multidisciplina',
                  'Finanzas, Adm. y CDG - Créditos y Cobros',
 'B2C Atención al Cliente - At. Presencial / At. Telefónica',
                                          'RRHH - Formación',
                             'Op. Comerciales - Facturación',
                    'Estrategia - Planificación Estratégica',
                       'Estrategia - Proyectos Estratégicos',
           'Soporte a la Dirección (Secretaria / Asistente)',
                      'Estrategia - Aceleración de Negocios',
                                                         nan,
                          'Finanzas, Adm. y CDG - Tesorería',
                                  'Compras (sin clasificar)',
                          'RRHH - Compensación y Beneficios',
                 'B2B Empresas y Pymes - Venta Especialista',
                         'B2C Ventas - Gestión Canal Online',
    'Calidad y Procesos - Mejora procesos y control calidad',
                       'Calidad y Procesos (sin clasificar)',
          'Calidad y Procesos - Generalista/Multidisciplina',
                'RRHH - Generalista RRHH / Business Partner',
 'B2C Atención al Cliente - Gest. calidad y satisf. cliente',
                          'Asesoría Jurídica - Especialidad',
           'Asesoría Jurídica - Generalista/Multidisciplina']
Length: 74, dtype: str

In [201]:
# Conteo absoluto y porcentaje por Área Funcional
conteo_area = df_julio['Área Funcional'].value_counts(dropna=False)
porcentaje_area = df_julio['Área Funcional'].value_counts(normalize=True, dropna=False) * 100

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_area, 'Porcentaje (%)': porcentaje_area})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

                                                    Cantidad  Porcentaje (%)
Área Funcional
NaN                                                    32436       66.973633
Red - Control de Operaciones de Red                     4200        8.672131
Red - Ingeniería de Red de Acceso y Troncal             3995        8.248849
B2B Empresas y Pymes - Ventas B2B                       1274        2.630547
B2C Ventas - Gestión Canal Telefónico                    872        1.800500
B2B Empresas y Pymes - Backoffice de Atención            560        1.156284
B2C Atención al Cliente - Backoffice                     426        0.879602
Red - Planificación Tecnológica                          386        0.797010
B2C Atención al Cliente - At. Presencial / At. ...       382        0.788751
TI - Aplicaciones/Desarrollo                             371        0.766038
B2B Empresas y Pymes - Preventa Grandes Cuentas          368        0.759844
B2C Marketing - Marketing de Producto                    291        0.600855
Calidad y Procesos - Mejora procesos y control ...       244        0.503810
Finanzas, Adm. y CDG - Créditos y Cobros                 190        0.392311
TI - Producción                                          177        0.365468
B2C Ventas - Gestión Canal Online                        163        0.336561
Op. Comerciales - Facturación                            158        0.326237
Finanzas, Adm. y CDG - Planificación Financiera          149        0.307654
B2B Empresas y Pymes - Planificación Comercial           149        0.307654
B2C Ventas - Gestión Canales Comerciales (Dir. ...       126        0.260164
B2B Empresas y Pymes - Marketing                          99        0.204415
Op. Comerciales - Soporte de Operaciones de Ventas        95        0.196155
RRHH - Generalista RRHH / Business Partner                85        0.175507
B2C Marketing - Planificación de Marketing                79        0.163119
B2C Marketing - Marketing de Clientes                     64        0.132147
RRHH - Relaciones Laborales y Sindicales                  59        0.121823
Negocio Mayorista - Gestión de Clientes                   58        0.119758
B2C Marketing - BI                                        58        0.119758
B2C Marketing (sin clasificar)                            52        0.107369
Negocio Mayorista - Ventas                                51        0.105304
Op. Comerciales - Logística y Distribucion                51        0.105304
Finanzas, Adm. y CDG - (sin clasificar)                   48        0.099110
Servicios Generales - Prestación de servicios             40        0.082592
B2B Empresas y Pymes - Preventa Generalista               40        0.082592
Asesoría Jurídica - Especialidad                          40        0.082592
Op. Comerciales - Adm. Comercial y Liq. Comisiones        38        0.078462
Seguridad y Prot. - Seguridad Física                      36        0.074333
TI - Estrategia y Gobierno                                36        0.074333
Compras (sin clasificar)                                  34        0.070203
B2C Marketing - Publicidad, Comunicación y Eventos        33        0.068138
Asesoría Jurídica (sin clasificar)                        32        0.066073
Asesoría Jurídica - Generalista/Multidisciplina           32        0.066073
Seguridad y Prot. - Continuidad de operaciones            28        0.057814
RRHH - Formación                                          28        0.057814
B2B Empresas y Pymes (sin clasificar)                     27        0.055749
RRHH - Talento y Desarrollo                               25        0.051620
B2C Marketing - Terminales                                22        0.045425
Estrategia - Planificación Estratégica                    19        0.039231
B2C Ventas - Planificación Comercial                      16        0.033037
Dentro de Convenio (sin clasificar)                       14        0.028907
Seguridad y Prot. - Generalista/Multidisciplina           13        0.026842
Estrategia - Proyectos Estratégicos                       13        0.026842
Media - Generalista/Multidisciplina                       12        0.024778
Negocio Mayorista - Generalista/Multidisciplina           12        0.024778
Red - Inst. y Manten. Red de Acceso y Troncal             10        0.020648
RRHH - Organización                                       10        0.020648
Auditoría y Control Int. - Auditoría                      10        0.020648
Auditoría y Control Int. - Intervención y Contr...        10        0.020648
Servicios Generales - Inmobiliario e instalaciones        10        0.020648
Direccion                                                  9        0.018583
Finanzas, Adm. y CDG - Tesorería                           8        0.016518
RRHH - Selección y Reclutamiento                           7        0.014454
Finanzas, Adm. y CDG - Generalista/Multidisciplina         7        0.014454
B2B Empresas y Pymes - Venta Especialista                  7        0.014454
Calidad y Procesos (sin clasificar)                        7        0.014454
RRHH - Planificación y Reporting                           6        0.012389
RRHH - Compensación y Beneficios                           6        0.012389
B2C Atención al Cliente - Gest. calidad y satis...         5        0.010324
Finanzas, Adm. y CDG - Planificación y Control ...         4        0.008259
Estrategia - Aceleración de Negocios                       3        0.006194
RRHH (sin clasificar)                                      2        0.004130
Estrategia - Generalista/Multidisciplina                   2        0.004130
Soporte a la Dirección (Secretaria / Asistente)            1        0.002065
Calidad y Procesos - Generalista/Multidisciplina           1        0.002065

In [202]:
df_areas.head()

                                             Cantidad  Porcentaje (%)
Área Funcional
NaN                                             32436       66.973633
Red - Control de Operaciones de Red              4200        8.672131
Red - Ingeniería de Red de Acceso y Troncal      3995        8.248849
B2B Empresas y Pymes - Ventas B2B                1274        2.630547
B2C Ventas - Gestión Canal Telefónico             872        1.800500

In [203]:
df_areas.tail()

                                                  Cantidad  Porcentaje (%)
Área Funcional
Estrategia - Aceleración de Negocios                     3        0.006194
RRHH (sin clasificar)                                    2        0.004130
Estrategia - Generalista/Multidisciplina                 2        0.004130
Soporte a la Dirección (Secretaria / Asistente)          1        0.002065
Calidad y Procesos - Generalista/Multidisciplina         1        0.002065

3) Localización Ciudad

In [204]:
df_julio[['Localización Ciudad', 'Localización País']].value_counts()

Localización Ciudad      Localización País
São Paulo                Brasil               5951
Curitiba                 Brasil               5920
MADRID                   España               5757
SÃO PAULO                Brasil               2122
Sao Paulo                Brasil               2010
BARCELONA                España               1863
Fortaleza                Brasil               1642
RIO DE JANEIRO           Brasil               1405
Maringá                  Brasil               1214
SEVILLA                  España                971
Belo Horizonte           Brasil                768
SAO PAULO                Brasil                646
VALENCIA                 España                620
Brasília                 Brasil                550
Recife                   Brasil                490
Goiania                  Brasil                478
VIZCAYA                  España                473
A CORUÑA                 España                427
ALICANTE                 España                425
Porto Alegre             Brasil                419
MALAGA                   España                379
SALVADOR                 Brasil                367
ASTURIAS                 España                322
VALLADOLID               España                299
Campinas                 Brasil                290
ZARAGOZA                 España                283
Campo Grande             Brasil                282
PONTEVEDRA               España                259
MURCIA                   España                253
BALEARES                 España                251
LAS PALMAS               España                244
BRASILIA                 Brasil                234
LEON                     España                216
GUIPUZCOA                España                216
Belem                    Brasil                200
TARRAGONA                España                192
VITORIA                  Brasil                191
Cuiaba                   Brasil                186
TENERIFE                 España                173
Brasilia                 Brasil                173
CADIZ                    España                163
Canoas                   Brasil                156
Guarulhos                Brasil                154
CORDOBA                  España                150
São José                 Brasil                149
CAMPINAS                 Brasil                149
GIRONA                   España                143
PORTO ALEGRE             Brasil                138
Osasco                   Brasil                127
Ribeirão Preto           Brasil                126
CANTABRIA                España                125
NAVARRA                  España                118
Joao Pessoa              Brasil                118
Santos                   Brasil                113
JOINVILLE                Brasil                113
CASTELLON                España                111
Sorocaba                 Brasil                110
GRANADA                  España                108
BADAJOZ                  España                103
Santana do Parnaíba      Brasil                100
Maringa                  Brasil                100
Bauru                    Brasil                 99
CURITIBA                 Brasil                 97
TOLEDO                   España                 95
ALMERIA                  España                 95
FEIRA DE SANTANA         Brasil                 93
Niterói                  Brasil                 92
Sao Luis                 Brasil                 86
HUELVA                   España                 85
LLEIDA                   España                 84
ALBACETE                 España                 84
OURENSE                  España                 81
JAEN                     España                 81
ARACAJU                  Brasil                 81
Londrina                 Brasil                 81
MANAUS                   Brasil                 80
Santo André              Brasil                 79
CIUDAD REAL              España                 77
ALAVA                    España                 76
Barueri                  Brasil                 76
Uberlandia               Brasil                 75
LUGO                     España                 72
Itajai                   Brasil                 71
Piracicaba               Brasil                 66
Juiz de Fora             Brasil                 63
RIBEIRAO PRETO           Brasil                 62
Ponta Grossa             Brasil                 62
SALAMANCA                España                 61
Dourados                 Brasil                 61
CACERES                  España                 60
Teresina                 Brasil                 60
FLORIANOPOLIS            Brasil                 60
BURGOS                   España                 59
Manaus                   Brasil                 59
Jundiaí                  Brasil                 58
Campina Grande           Brasil                 58
Cascavel                 Brasil                 56
GUADALAJARA              España                 54
VOLTA REDONDA            Brasil                 52
Natal                    Brasil                 49
Blumenau                 Brasil                 49
Maceio                   Brasil                 49
Mogi das Cruzes          Brasil                 47
Caxias do Sul            Brasil                 45
LONDRINA                 Brasil                 44
SANTO ANDRE              Brasil                 44
Mauá                     Brasil                 44
Araraquara               Brasil                 43
HUESCA                   España                 42
SEGOVIA                  España                 42
Nova Iguaçu              Brasil                 42
Sao Jose do Rio Preto    Brasil                 42
São Bernardo do Campo    Brasil                 42
VILA VELHA               Brasil                 42
Porto Velho              Brasil                 41
Rio Branco               Brasil                 40
SORIA                    España                 39
Divinopolis              Brasil                 39
MARINGA                  Brasil                 39
GUARULHOS                Brasil                 38
Foz do Iguaçu            Brasil                 37
JUNDIAI                  Brasil                 36
Governador Valadares     Brasil                 36
ZAMORA                   España                 35
VITORIA DA CONQUISTA     Brasil                 35
Rondonopolis             Brasil                 35
TERUEL                   España                 34
PALENCIA                 España                 34
Varginha                 Brasil                 34
Chapeco                  Brasil                 34
CAMPOS GOYTACAZES        Brasil                 34
Indaiatuba               Brasil                 33
SAO JOSE DO RIO PRETO    Brasil                 33
NITEROI                  Brasil                 33
LA RIOJA                 España                 32
Pelotas                  Brasil                 32
Salvador                 Brasil                 31
Sao Jose                 Brasil                 31
Sao Jose dos Campos      Brasil                 30
MARILIA                  Brasil                 30
Pocos de Caldas          Brasil                 30
CUENCA                   España                 29
Montes Claros            Brasil                 29
Palmas                   Brasil                 29
Santa Maria              Brasil                 29
Lages                    Brasil                 29
Aparecida de Goiania     Brasil                 29
SANTOS                   Brasil                 29
SAO JOSE RIO PRETO       Brasil                 29
NOVA IGUACU              Brasil                 29
FORTALEZA                Brasil                 29
Rio Verde                Brasil                 28
Anápolis                 Brasil                 28
SAO BERNARDO DO CAMPO    Brasil                 28
PETROLINA                Brasil                 27
MOGI DAS CRUZES          Brasil                 27
CACHOEIRO DE ITAPEMIRIM  Brasil                 27
PONTA GROSSA             Brasil                 27
Presidente Prudente SP   Brasil                 26
CAXIAS DO SUL            Brasil                 26
Santarem                 Brasil                 25
Sete Lagoas              Brasil                 25
São Gonçalo              Brasil                 25
Votorantim               Brasil                 25
ARARAQUARA               Brasil                 24
Sinop                    Brasil                 24
ITABUNA                  Brasil                 24
Macapa                   Brasil                 24
Imperatriz               Brasil                 24
Criciuma                 Brasil                 24
OSASCO                   Brasil                 24
PIRACICABA               Brasil                 24
CONTAGEM                 Brasil                 24
PASSO FUNDO              Brasil                 24
AVILA                    España                 23
Novo Hamburgo            Brasil                 23
BLUMENAU                 Brasil                 23
CABO FRIO                Brasil                 23
Maraba                   Brasil                 22
Boa Vista                Brasil                 22
ARACATUBA                Brasil                 21
SERRA                    Brasil                 21
Joinville                Brasil                 21
São Luis                 Brasil                 21
SANTA MARIA              Brasil                 20
Pouso Alegre             Brasil                 20
BELEM                    Brasil                 20
Guarapari                Brasil                 19
PRAIA GRANDE             Brasil                 19
SAO VICENTE              Brasil                 19
CASCAVEL                 Brasil                 19
SUZANO                   Brasil                 18
MAUA                     Brasil                 18
SAO CARLOS               Brasil                 18
COLATINA                 Brasil                 18
ITAJAI                   Brasil                 18
SAO JOSE CAMPOS          Brasil                 17
Guaruja                  Brasil                 17
Macae                    Brasil                 17
CARIACICA                Brasil                 17
CANOAS                   Brasil                 17
SANTA CRUZ DO SUL        Brasil                 17
LINHARES                 Brasil                 16
Betim                    Brasil                 16
Taboao da Serra          Brasil                 15
Campos dos Goytacazes    Brasil                 15
JAU                      Brasil                 15
SÃO CAETANO DO SUL       Brasil                 15
NOVO HAMBURGO            Brasil                 15
Pinhais                  Brasil                 14
Ourinhos                 Brasil                 14
Marília                  Brasil                 14
SÃO MATEUS               Brasil                 14
Patos de Minas           Brasil                 14
Conselheiro Lafaiete     Brasil                 14
CARUARU                  Brasil                 14
São Jose dos Pinhais     Brasil                 14
BENTO GONCALVES          Brasil                 14
CRICIUMA                 Brasil                 14
BALNEÁRIO CAMBORIU       Brasil                 14
Redencao                 Brasil                 14
DUQUE DE CAXIAS          Brasil                 13
JARAGUA DO SUL           Brasil                 13
S J Campos               Brasil                 13
NOVA VENECIA             Brasil                 13
Aracajú                  Brasil                 13
Jaboatão dos Guararapes  Brasil                 13
Uruguaiana               Brasil                 13
CHAPECO                  Brasil                 13
Caruaru                  Brasil                 12
Florianópolis            Brasil                 12
Passos                   Brasil                 12
Catalao                  Brasil                 12
Guaiba                   Brasil                 12
TUBARAO                  Brasil                 12
FOZ DO IGUACU            Brasil                 12
Ipatinga                 Brasil                 11
TAUBATE                  Brasil                 11
Mossoró                  Brasil                 11
Maceió                   Brasil                 10
GRAVATAI                 Brasil                 10
Erechim                  Brasil                 10
PALMAS                   Brasil                  9
RIO BRANCO               Brasil                  9
Guarapuava               Brasil                  9
Aracaju                  Brasil                  9
NOVA SANTA RITA          Brasil                  9
PORTO SEGURO             Brasil                  9
BARREIRAS                Brasil                  9
CACHOEIRINHA             Brasil                  9
LAGES                    Brasil                  9
CAMACARI                 Brasil                  8
Franca                   Brasil                  8
Juazeiro do Norte        Brasil                  8
ILHEUS                   Brasil                  8
Araguaina                Brasil                  8
Gurupi                   Brasil                  8
Tubarão                  Brasil                  8
SAO JOSE DOS CAMPOS      Brasil                  7
BAURU                    Brasil                  7
PRESIDENTE PRUDENTE      Brasil                  7
Nilopolis                Brasil                  7
Passo Fundo              Brasil                  7
TEIXEIRA DE FREITAS      Brasil                  7
GARANHUNS                Brasil                  6
Taubate                  Brasil                  6
ALAGOINHAS               Brasil                  6
Goiânia                  Brasil                  5
Santo Angelo             Brasil                  5
Santa Cruz do Sul        Brasil                  5
NATAL                    Brasil                  4
Linhares                 Brasil                  4
Colatina                 Brasil                  4
Contagem                 Brasil                  4
SAO JOSE                 Brasil                  3
Cuiabá                   Brasil                  3
Paranaguá                Brasil                  3
Embu das Artes           Brasil                  3
Macapá                   Brasil                  3
UMUARAMA                 Brasil                  2
Parnamirim               Brasil                  2
D. CENTRAL               España                  1
Praia Grande             Brasil                  1
APARECIDA DE GOIANIA     Brasil                  1
RESENDE                  Brasil                  1
DUQUE DE CAXIAS RJ       Brasil                  1
Tangara da Serra         Brasil                  1
Bento Gonçalves          Brasil                  1
SÃO JOSÉ                 Brasil                  1
Itajaí                   Brasil                  1
Name: count, dtype: int64

In [205]:
# a la hora de verlo vemos que sao paula y varias ciudades mas estan escritas de varias formas, por lo que los datos no son fidedignos

In [206]:
df_julio[['Localización Ciudad', 'Localización País']].value_counts().head()
# lmismas ciudades escritas de varias formas, daatos no fidedignos mientras no se cambien los nombres

Localización Ciudad  Localización País
São Paulo            Brasil               5951
Curitiba             Brasil               5920
MADRID               España               5757
SÃO PAULO            Brasil               2122
Sao Paulo            Brasil               2010
Name: count, dtype: int64

In [207]:
df_julio[['Localización Ciudad', 'Localización País']].tail()
# lmismas ciudades escritas de varias formas, daatos no fidedignos mientras no se cambien los nombres

      Localización Ciudad Localización País
48426           São Paulo            Brasil
48427           Sao Paulo            Brasil
48428           São Paulo            Brasil
48429      RIO DE JANEIRO            Brasil
48430           São Paulo            Brasil

4) Subadctividad_desc

In [208]:
df_julio['Subactividad_desc'].unique()

<StringArray>
[                                                     'tecnologíayplanificación',
                                                             'gestionydireccion',
                                                          'vigilanciayseguridad',
                                             'tesoreríayplanificaciónfinanciera',
                                                            'talentoydesarrollo',
                                                              'supervisióndered',
                                                                 'soporteventas',
                                                                  'soportedered',
                                                                     'selección',
                                                     'restodeserviciosgenerales',
                                             'relacionesregulatoriasynormativas',
                                          'relacioneslaboralesygestióndealiados',
                                           'relacionescongobiernoeinstituciones',
                                                                  'producciónit',
                                                                    'pre-ventas',
                                                     'planificaciónycontrolling',
                                          'planificacióneinteligenciadelnegocio',
                                          'organización,planificaciónyreporting',
                                                    'operacionesredparaempresas',
                                                                'operacióndered',
                   'marketingdeproducto(diseñoydesarrollodeproductosyservicios)',
 'marketingdecliente(ofertacomercial,captaciónyfidelización,pricing,terminales)',
                                             'marcaypublicidad(noinstitucional)',
                                   'logísticadeterminalesyequipamientodecliente',
                                                                'logísticadered',
                                                        'intervenciónyauditoria',
                                                                    'innovación',
                         'ingenieríayconstruccióndeinfraestructurasderedtroncal',
                        'ingenieríayconstruccióndeinfraestructurasdereddeacceso',
                                                                      'helpdesk',
                                                                    'gobiernoit',
                                              'gestiónymantenimientodeedificios',
                                                      'gestiónfiscalytributaria',
                                                          'gestióndelaoperadora',
                                                  'gestióndelamorosidadeimpagos',
                                                       'fuerzadeventasindirecta',
                                                         'fuerzadeventasdirecta',
                                                                     'formación',
                                                                   'facturación',
                                                         'estrategiacorporativa',
                              'desarrollodeproyectosestratégicosytransformación',
                                                                  'contabilidad',
                                           'comunicación,culturaytransformación',
                                                                       'compras',
                                       'compensación,beneficiosymovilidadglobal',
                                                     'canaltelefónico-comercial',
                                                      'canaltelefónico-atención',
                    'canalpresencial-comercialdistribuidorespecialistaexclusivo',
                                           'canalonlineydeautogestión-comercial',
                                            'canalonlineydeautogestión-atención',
                                                             'callcentertécnico',
                                                'calidadyoptimizacióndeprocesos',
                                                              'businesspartners',
                                                                    'backoffice',
                                                 'asesoríalegalysoportejurídico',
                                       'aseguramientodeingresosycontroldefraude',
                                                  'apoyoalagestióndelaoperadora',
                                                       'aplicaciones/desarrollo',
                                                'administraciónygestióndecobros',
                                                              'gestióndeseguros',
                                                         'relaciónconinversores',
                                                            'mercadodecapitales',
                                                     'administracióndelpersonal',
                                                                        'nómina',
                      'responsabilidadsocialcorporativaypatrocinioscorporativos',
                              'instalaciónymantenimientoreddeacceso(redexterna)',
                                           'mantenimientoredtroncal(redinterna)',
                                                           'gestióndecontenidos',
                                               'fusiones,adquisicionesyalianzas',
                                                                'comunicaciones']
Length: 70, dtype: str

In [209]:
# Conteo absoluto y porcentaje por Área Funcional
conteo_subactividad = df_julio['Subactividad_desc'].value_counts(dropna=False)
porcentaje_subactividad= df_julio['Subactividad_desc'].value_counts(normalize=True, dropna=False) * 100

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_subactividad, 'Porcentaje (%)': porcentaje_subactividad})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

                                                    Cantidad  Porcentaje (%)
Subactividad_desc
fuerzadeventasdirecta                                   7503       15.492143
instalaciónymantenimientoreddeacceso(redexterna)        5973       12.333010
canaltelefónico-atención                                5418       11.187050
ingenieríayconstruccióndeinfraestructurasderedt...      3416        7.053334
operacióndered                                          2129        4.395945
callcentertécnico                                       2107        4.350519
producciónit                                            1999        4.127522
operacionesredparaempresas                              1967        4.061448
backoffice                                              1861        3.842580
canaltelefónico-comercial                               1836        3.790960
ingenieríayconstruccióndeinfraestructurasderedd...      1457        3.008404
soporteventas                                           1037        2.141191
fuerzadeventasindirecta                                  896        1.850055
mantenimientoredtroncal(redinterna)                      752        1.552724
soportedered                                             747        1.542401
planificacióneinteligenciadelnegocio                     722        1.490781
marketingdecliente(ofertacomercial,captaciónyfi...       690        1.424707
marketingdeproducto(diseñoydesarrollodeproducto...       641        1.323532
tecnologíayplanificación                                 614        1.267783
pre-ventas                                               568        1.172803
supervisióndered                                         565        1.166608
calidadyoptimizacióndeprocesos                           511        1.055109
planificaciónycontrolling                                476        0.982842
desarrollodeproyectosestratégicosytransformación         421        0.869278
aplicaciones/desarrollo                                  415        0.856889
aseguramientodeingresosycontroldefraude                  311        0.642151
logísticadeterminalesyequipamientodecliente              307        0.633892
asesoríalegalysoportejurídico                            269        0.555429
administraciónygestióndecobros                           260        0.536846
facturación                                              172        0.355144
businesspartners                                         170        0.351015
canalonlineydeautogestión-comercial                      146        0.301460
formación                                                139        0.287006
logísticadered                                           131        0.270488
gestiónfiscalytributaria                                 125        0.258099
compras                                                  124        0.256034
contabilidad                                             123        0.253970
relacioneslaboralesygestióndealiados                     114        0.235386
gestiónymantenimientodeedificios                         113        0.233322
intervenciónyauditoria                                   102        0.210609
relacionesregulatoriasynormativas                         81        0.167248
gestióndecontenidos                                       77        0.158989
canalpresencial-comercialdistribuidorespecialis...        75        0.154859
compensación,beneficiosymovilidadglobal                   74        0.152795
gestióndelamorosidadeimpagos                              71        0.146600
vigilanciayseguridad                                      65        0.134212
canalonlineydeautogestión-atención                        57        0.117693
administracióndelpersonal                                 56        0.115628
selección                                                 54        0.111499
estrategiacorporativa                                     51        0.105304
marcaypublicidad(noinstitucional)                         46        0.094980
relacionescongobiernoeinstituciones                       43        0.088786
restodeserviciosgenerales                                 42        0.086721
comunicación,culturaytransformación                       40        0.082592
tesoreríayplanificaciónfinanciera                         35        0.072268
gestióndeseguros                                          26        0.053685
organización,planificaciónyreporting                      25        0.051620
comunicaciones                                            25        0.051620
talentoydesarrollo                                        21        0.043361
gobiernoit                                                20        0.041296
nómina                                                    18        0.037166
responsabilidadsocialcorporativaypatrocinioscor...        17        0.035101
gestióndelaoperadora                                      15        0.030972
helpdesk                                                  14        0.028907
mercadodecapitales                                        14        0.028907
gestionydireccion                                          9        0.018583
fusiones,adquisicionesyalianzas                            9        0.018583
innovación                                                 8        0.016518
apoyoalagestióndelaoperadora                               8        0.016518
relaciónconinversores                                      8        0.016518

5) año

In [210]:
df_julio['Año'].unique()

array([2019])

6) COD. UNIDAD DE NEGOCIO

In [211]:
df_julio['COD. UNIDAD DE NEGOCIO'].unique()

array([156, 185])

In [212]:
df_julio['COD. UNIDAD DE NEGOCIO'].value_counts()

COD. UNIDAD DE NEGOCIO
185    32412
156    16019
Name: count, dtype: int64

In [213]:
df_julio['COD. UNIDAD DE NEGOCIO'].value_counts(normalize=True) * 100

COD. UNIDAD DE NEGOCIO
185    66.924078
156    33.075922
Name: proportion, dtype: float64

7) Mes

In [214]:
df_julio['Mes'].unique()

<StringArray>
['Jul']
Length: 1, dtype: str

8) Reducción de Jormada

In [215]:
df_julio['Reducción de Jormada'].unique()

<StringArray>
['No', 'Sí']
Length: 2, dtype: str

In [216]:
df_julio['Reducción de Jormada'].value_counts(normalize=True)*100 # solo el 0.95% tiene reduccion de jornada

Reducción de Jormada
No    99.044001
Sí     0.955999
Name: proportion, dtype: float64

 9) Tipo de contrato

In [217]:
df_julio['Tipo de contrato'].unique()

<StringArray>
['Fijo']
Length: 1, dtype: str

10) División

In [218]:
df_julio['División'].unique() 
#28 divisiones las que tiene BRA delante es de brasil

<StringArray>
[                    'OPERACIONES, RED Y TI',
                    'CONSEJERA DELEGADA COO',
                                'ESTRATEGIA',
                  'TERRITORIAL MEDITERRANEO',
        'TERRITORIAL CENTRO Y SECTORES GGCC',
         'SEGURIDAD Y PREVENCION DEL FRAUDE',
             'FINANZAS Y CONTROL DE GESTION',
                          'RECURSOS HUMANOS',
                           'TERRITORIAL SUR',
                         'TERRITORIAL NORTE',
          'DESARROLLO DE NEGOCIO MULTIMARCA',
                  'CALIDAD Y TRANSFORMACION',
           'SECRETARIO GENERAL Y REGULACION',
                              'VIDEO ESPAÑA',
      'AUDITORIA, INSPECCION E INTERVENCION',
                         'BRA - Presidencia',
         'BRA_VP de Relacoes Institucionais',
             'BRA - Chief Financial Officer',
                          'BRA - VP Pessoas',
                         'BRA - VP Juridico',
            'BRA - VP Assuntos Regulatórios',
            'BRA - VP Tecnologia Informacao',
 'BRA - VP Engenharia e Servicos ao Cliente',
  'BRA - VP Dados e Inteligencia Artificial',
           'BRA - VP Atendimento ao Cliente',
                              'BRA - VP B2C',
                    'BRA - VP B2B e Atacado',
        'BRA - VP Transformacao e Qualidade']
Length: 28, dtype: str

In [219]:
# Conteo absoluto y porcentaje por Divion
conteo_division = df_julio['División'].value_counts(dropna=False)
porcentaje_division= df_julio['División'].value_counts(normalize=True, dropna=False) * 100

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_division, 'Porcentaje (%)': porcentaje_division})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

# se ve por orden las que mas personas trabajan y las que menos

                                           Cantidad  Porcentaje (%)
División
BRA - VP Engenharia e Servicos ao Cliente     11434       23.608846
OPERACIONES, RED Y TI                          9174       18.942413
BRA - VP B2C                                   7563       15.616031
BRA - VP Atendimento ao Cliente                6309       13.026780
BRA - VP B2B e Atacado                         2685        5.543970
CONSEJERA DELEGADA COO                         2152        4.443435
BRA - VP Tecnologia Informacao                 1856        3.832256
BRA - Chief Financial Officer                  1115        2.302244
TERRITORIAL CENTRO Y SECTORES GGCC             1087        2.244430
TERRITORIAL MEDITERRANEO                       1018        2.101959
TERRITORIAL SUR                                 676        1.395800
TERRITORIAL NORTE                               596        1.230617
BRA - VP Pessoas                                537        1.108794
FINANZAS Y CONTROL DE GESTION                   447        0.922963
BRA - VP Dados e Inteligencia Artificial        272        0.561624
SEGURIDAD Y PREVENCION DEL FRAUDE               255        0.526522
BRA - VP Transformacao e Qualidade              244        0.503810
ESTRATEGIA                                      241        0.497615
BRA - VP Juridico                               212        0.437736
RECURSOS HUMANOS                                164        0.338626
BRA - VP Assuntos Regulatórios                  112        0.231257
CALIDAD Y TRANSFORMACION                         97        0.200285
BRA - Presidencia                                72        0.148665
SECRETARIO GENERAL Y REGULACION                  71        0.146600
AUDITORIA, INSPECCION E INTERVENCION             20        0.041296
VIDEO ESPAÑA                                     12        0.024778
DESARROLLO DE NEGOCIO MULTIMARCA                  9        0.018583
BRA_VP de Relacoes Institucionais                 1        0.002065

11) Subactividad

In [220]:
# da exastamente lo mismo que subactividad_des, columna copiada

In [221]:
df_julio['Subactividad'].unique()

<StringArray>
[                                                            'Tecnología y Planificación',
                                                                    'Gestión y Direccion',
                                                                 'Vigilancia y Seguridad',
                                                   'Tesorería y planificación financiera',
                                                                   'Talento y Desarrollo',
                                                                     'Supervisión de red',
                                                                         'Soporte ventas',
                                                                         'Soporte de Red',
                                                                              'Selección',
                                                           'Resto de servicios generales',
                                                   'Relaciones regulatorias y normativas',
                                              'Relaciones Laborales y Gestión de Aliados',
                                                'Relaciones con gobierno e instituciones',
                                                                          'Producción IT',
                                                                             'Pre-Ventas',
                                                            'Planificación y controlling',
                                               'Planificación e Inteligencia del Negocio',
                                                'Organización, Planificación y Reporting',
                                                          'Operaciones Red para empresas',
                                                                       'Operación de red',
                   'Marketing de Producto (Diseño y desarrollo de productos y servicios)',
 'Marketing de Cliente (Oferta Comercial, Captación y fidelización, Pricing, Terminales)',
                                                  'Marca y Publicidad (no institucional)',
                                      'Logística de terminales y equipamiento de cliente',
                                                                       'Logística de red',
                                                               'Intervención y Auditoria',
                                                                             'Innovación',
                           'Ingeniería y construcción de infraestructuras de Red Troncal',
                         'Ingeniería y construcción de infraestructuras de Red de Acceso',
                                                                              'Help Desk',
                                                                            'Gobierno IT',
                                                   'Gestión y mantenimiento de edificios',
                                                            'Gestión fiscal y tributaria',
                                                                'Gestión de la operadora',
                                                      'Gestión de la morosidad e Impagos',
                                                             'Fuerza de ventas indirecta',
                                                               'Fuerza de ventas directa',
                                                                              'Formación',
                                                                            'Facturación',
                                                                 'Estrategia corporativa',
                                  'Desarrollo de Proyectos Estratégicos y Transformación',
                                                                           'Contabilidad',
                                                 'Comunicación, Cultura y Transformación',
                                                                                'Compras',
                                            'Compensación, Beneficios y Movilidad Global',
                                                           'Canal telefónico - Comercial',
                                                            'Canal telefónico - Atención',
                       'Canal presencial - Comercial distribuidor especialista exclusivo',
                                              'Canal Online y de Autogestión - Comercial',
                                               'Canal Online y de Autogestión - Atención',
                                                                    'Call Center técnico',
                                                     'Calidad y Optimización de procesos',
                                                                      'Business Partners',
                                                                             'Backoffice',
                                                      'Asesoría legal y soporte jurídico',
                                          'Aseguramiento de ingresos y control de fraude',
                                                     'Apoyo a la gestión de la operadora',
                                                                'Aplicaciones/Desarrollo',
                                                     'Administración y gestión de cobros',
                                                                     'Gestión de Seguros',
                                                                'Relación con Inversores',
                                                                   'Mercado de Capitales',
                                                            'Administración del personal',
                                                                                 'Nómina',
                          'Responsabilidad Social Corporativa y Patrocinios Corporativos',
                                'Instalación y mantenimiento Red de Acceso (Red Externa)',
                                                'Mantenimiento Red Troncal (Red Interna)',
                                                                  'Gestión de Contenidos',
                                                     'Fusiones, Adquisiciones y Alianzas',
                                                                         'Comunicaciones']
Length: 70, dtype: str

In [222]:
# Conteo absoluto y porcentaje por Área Funcional
conteo_subactividad1 = df_julio['Subactividad'].value_counts(dropna=False)
porcentaje_subactividad1= df_julio['Subactividad'].value_counts(normalize=True, dropna=False) * 100

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_subactividad1, 'Porcentaje (%)': porcentaje_subactividad1})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

                                                    Cantidad  Porcentaje (%)
Subactividad
Fuerza de ventas directa                                7503       15.492143
Instalación y mantenimiento Red de Acceso (Red ...      5973       12.333010
Canal telefónico - Atención                             5418       11.187050
Ingeniería y construcción de infraestructuras d...      3416        7.053334
Operación de red                                        2129        4.395945
Call Center técnico                                     2107        4.350519
Producción IT                                           1999        4.127522
Operaciones Red para empresas                           1967        4.061448
Backoffice                                              1861        3.842580
Canal telefónico - Comercial                            1836        3.790960
Ingeniería y construcción de infraestructuras d...      1457        3.008404
Soporte ventas                                          1037        2.141191
Fuerza de ventas indirecta                               896        1.850055
Mantenimiento Red Troncal (Red Interna)                  752        1.552724
Soporte de Red                                           747        1.542401
Planificación e Inteligencia del Negocio                 722        1.490781
Marketing de Cliente (Oferta Comercial, Captaci...       690        1.424707
Marketing de Producto (Diseño y desarrollo de p...       641        1.323532
Tecnología y Planificación                               614        1.267783
Pre-Ventas                                               568        1.172803
Supervisión de red                                       565        1.166608
Calidad y Optimización de procesos                       511        1.055109
Planificación y controlling                              476        0.982842
Desarrollo de Proyectos Estratégicos y Transfor...       421        0.869278
Aplicaciones/Desarrollo                                  415        0.856889
Aseguramiento de ingresos y control de fraude            311        0.642151
Logística de terminales y equipamiento de cliente        307        0.633892
Asesoría legal y soporte jurídico                        269        0.555429
Administración y gestión de cobros                       260        0.536846
Facturación                                              172        0.355144
Business Partners                                        170        0.351015
Canal Online y de Autogestión - Comercial                146        0.301460
Formación                                                139        0.287006
Logística de red                                         131        0.270488
Gestión fiscal y tributaria                              125        0.258099
Compras                                                  124        0.256034
Contabilidad                                             123        0.253970
Relaciones Laborales y Gestión de Aliados                114        0.235386
Gestión y mantenimiento de edificios                     113        0.233322
Intervención y Auditoria                                 102        0.210609
Relaciones regulatorias y normativas                      81        0.167248
Gestión de Contenidos                                     77        0.158989
Canal presencial - Comercial distribuidor espec...        75        0.154859
Compensación, Beneficios y Movilidad Global               74        0.152795
Gestión de la morosidad e Impagos                         71        0.146600
Vigilancia y Seguridad                                    65        0.134212
Canal Online y de Autogestión - Atención                  57        0.117693
Administración del personal                               56        0.115628
Selección                                                 54        0.111499
Estrategia corporativa                                    51        0.105304
Marca y Publicidad (no institucional)                     46        0.094980
Relaciones con gobierno e instituciones                   43        0.088786
Resto de servicios generales                              42        0.086721
Comunicación, Cultura y Transformación                    40        0.082592
Tesorería y planificación financiera                      35        0.072268
Gestión de Seguros                                        26        0.053685
Organización, Planificación y Reporting                   25        0.051620
Comunicaciones                                            25        0.051620
Talento y Desarrollo                                      21        0.043361
Gobierno IT                                               20        0.041296
Nómina                                                    18        0.037166
Responsabilidad Social Corporativa y Patrocinio...        17        0.035101
Gestión de la operadora                                   15        0.030972
Help Desk                                                 14        0.028907
Mercado de Capitales                                      14        0.028907
Gestión y Direccion                                        9        0.018583
Fusiones, Adquisiciones y Alianzas                         9        0.018583
Innovación                                                 8        0.016518
Apoyo a la gestión de la operadora                         8        0.016518
Relación con Inversores                                    8        0.016518

12) Género

In [223]:
df_julio['Género'].unique()

<StringArray>
['M', 'F']
Length: 2, dtype: str

In [224]:
round(df_julio['Género'].value_counts(normalize=True)*100,2)

Género
M    63.07
F    36.93
Name: proportion, dtype: float64

 13) Departamento

In [225]:
df_julio['Departamento'].unique()

<StringArray>
['ESTRAT. Y DESARR. DE RED E INFRAESTR. TI',
                                'MAYORISTA',
   'PLANIFICACION NEGOCIO Y TRANSF DIGITAL',
                'GRAN PUBLICO MEDITERRANEO',
                          'CANALES ON LINE',
                  'GRANDES CLIENTES CENTRO',
         'SECTOR AAPP, DEFENSA Y SEGURIDAD',
                        'SEGURIDAD DIGITAL',
                                        nan,
                'FINANZAS, RIESGO Y COBROS',
 ...
                  'BRA_Ger de Planejamento',
           'BRA_Ger De Servicos Essenciais',
         'BRA_Ger Sr Serv Financ e Seguros',
        'BRA_Coord De Servicos Financeiros',
           'BRA_Ger Seguros e Assistencias',
    'BRA_Ger De Novos Servicos Financeiros',
                      'BRA_Ger Sr Inovacao',
      'BRA_Ger Desenvolvimento de Negocios',
                         'BRA_Ger Inovacao',
                          'BRA_Presidencia']
Length: 3319, dtype: str

In [226]:
# Conteo absoluto y porcentaje por Departamento
conteo_departamento = df_julio['Departamento'].value_counts(dropna=False)
porcentaje_departamente=round( df_julio['Departamento'].value_counts(normalize=True, dropna=False) * 100,2)

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_departamento, 'Porcentaje (%)': porcentaje_departamente})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

                                           Cantidad  Porcentaje (%)
Departamento
OPERACIONES                                    4927           10.17
SOPORTE Y EXPL. RED,SERVICIOS Y SISTEMAS       1488            3.07
POSTVENTA                                      1360            2.81
EMPRESAS                                       1251            2.58
ESTRAT. Y DESARR. DE RED E INFRAESTR. TI        922            1.90
GRAN PUBLICO Y PYMES SUR                        452            0.93
NaN                                             445            0.92
GRAN PUBLICO CENTRO                             410            0.85
GRAN PUBLICO MEDITERRANEO                       352            0.73
GRAN PUBLICO                                    345            0.71
GGCC Y EMPRESAS ESTE                            295            0.61
GGCC Y EMPRESAS CATALUÑA                        262            0.54
DESARROLLO DE SISTEMAS                          255            0.53
PEQUEÑA Y MEDIANA PRESENCIAL CENTRO             235            0.49
FINANZAS, RIESGO Y COBROS                       230            0.47
EMPRESAS NORTE                                  206            0.43
SEGURIDAD DIGITAL                               205            0.42
CANALES ON LINE                                 164            0.34
FACTURACION, SOPORTE E IMPLANT. TELCO           158            0.33
GRAN PUBLICO NORTE                              152            0.31
CHIEF DATA OFFICER TE                           146            0.30
MAYORISTA                                       124            0.26
BRA_Ger Suporte Operacoes 12                    120            0.25
DESARROLLO TELCO EMPRESAS                       119            0.25
SECTOR INDUSTRIA, SERVICIOS Y RETAIL            109            0.23
EMPRESAS SUR                                    108            0.22
SECTOR BANCA, SEGUROS, OCIO Y TURISMO           107            0.22
SECTOR AAPP, DEFENSA Y SEGURIDAD                106            0.22
DESARROLLO DE SERVICIOS                         100            0.21
GRANDES CLIENTES CENTRO                          95            0.20
BRA_Ger Suporte Operacoes 02                     93            0.19
BRA_Ger Suporte Operacoes 06                     91            0.19
DELEGADO CANARIAS                                86            0.18
SERVICIOS DIGITALES Y AAPP                       76            0.16
TERMINALES Y LOGISTICA                           72            0.15
PLANIFICACION NEGOCIO Y TRANSF DIGITAL           70            0.14
BRA_Ger Suporte Operacoes 14                     64            0.13
SOPORTE A LA DECISION OPERATIVA                  63            0.13
BRA_Ger Suporte Operacoes 04                     63            0.13
BRA_Coord Agend e Controle - Luz 01              61            0.13
CULTURA, TALENTO Y COMUNICACION INTERNA          60            0.12
BRA_Ger Suporte Operacoes 08                     60            0.12
RELACIONES LABORALES                             59            0.12
PLANIFICACION, CONTROL Y REPORTING               57            0.12
BRA_Ger Televendas 01                            54            0.11
ADMINISTRACIONES PUBLICAS Y GGEE NORTE           53            0.11
BRA_Coord Serv Cliente - ABC/M Cruzes 01         52            0.11
BRA_Sup Manut Cw 018                             51            0.11
SOPORTE A LA DECISION TERRIT. Y SECTORES         50            0.10
BRA_LOJA CNB SHOPPING                            48            0.10
BRA_Loja Megastore Barra Shopping                47            0.10
BRA_Coord Operacoes - BH                         45            0.09
BRA_Loja Shopping Morumbi                        44            0.09
BRA_Coord Novos Projetos Rede Externa            43            0.09
BRA_Sup Operacoes Proprias 154                   43            0.09
BRA_LOJA TAGUATINGA SHOPPING                     43            0.09
BRA_Sup Operacoes Proprias 132                   42            0.09
BRA_Loja Centro                                  42            0.09
BRA_Coord Equipamentos - RS                      41            0.08
BRA_Ger Suporte Operacoes 15                     41            0.08
SERV. GENERALES Y GESTION DE ESPACIOS            40            0.08
SERVICIOS JURIDICOS                              40            0.08
BRA_Coord Atend CO - Curitiba 02                 40            0.08
BRA_Coord Equipamentos - Cs                      40            0.08
BRA_SUP OPERACOES PROPRIAS 26                    40            0.08
BRA_COORD RELACIONAMENTO COM CLIENTE I           40            0.08
BRA_Loja Amazonas Shopping                       40            0.08
BRA_Sup Atend CO - São Paulo 03                  39            0.08
BRA_Sup Operacoes Proprias 14                    39            0.08
BRA_Sup Operacoes Proprias 104                   39            0.08
BRA_Loja Norte Shopping                          39            0.08
BRA_Sup Atend COE - São Paulo 01                 37            0.08
BRA_SUP INSTAL SE 005                            37            0.08
BRA_Sup Agend e Controle - Luz 02_02             37            0.08
BRA_Sup Operacoes Proprias 33                    37            0.08
BRA_Loja Shopping Eldorado                       37            0.08
BRA_Loja Shopping Ibirapuera                     36            0.07
BRA_Loja Rio Sul                                 36            0.07
BRA_Loja Tijuca                                  36            0.07
BRA_Loja Flamboyant                              36            0.07
BRA_GER O&M RF REGIONAL                          35            0.07
BRA_GER O&M TX REGIONAL                          35            0.07
BRA_Ger O&M Rede de Acesso SPC                   35            0.07
BRA_Loja Shopping Paulista                       35            0.07
BRA_Loja Shopping Vitoria                        35            0.07
MARKETING, COMUNICACION Y CREATIVIDAD            34            0.07
BRA_Coord Serv ao Cliente B2B - SC               34            0.07
BRA_Sup Agend e Controle Luz 02 03               34            0.07
BRA_Sup Operacoes Proprias 179                   34            0.07
BRA_Sup Operacoes Proprias 06                    34            0.07
BRA_COORD SERV AO CLIENTE - CWB I                33            0.07
BRA_Loja Niteroi Plaza                           33            0.07
BRA_Sup Back Office - Curtiba 03                 32            0.07
BRA_Sup Atend CO - São Paulo 12                  32            0.07
BRA_Coord Serv ao Cliente - Brasilia M           32            0.07
BRA_Sup Serv Cliente - Freguesia 03_07           32            0.07
BRA_Sup Televendas 01                            32            0.07
BRA_Sup Operacoes Proprias 160                   32            0.07
BRA_Sup ODC 09                                   32            0.07
BRA_SUP ODC 19                                   32            0.07
BRA_Loja Shopping Praia Da Costa                 32            0.07
BRA_Loja Bh Shopping                             32            0.07
BRA_Loja Shop Praia De Belas                     32            0.07
BRA_Funcs Cedidos P/ o Sindicato                 31            0.06
BRA_Ger O&M Rede IP Core                         31            0.06
BRA_Sup Atend COE - Curitiba 06                  31            0.06
BRA_Sup B2B Fixo                                 31            0.06
BRA_Sup Manut SE 021                             31            0.06
BRA_Coord Serv ao Cliente - RJ I                 31            0.06
BRA_Sup Operacoes Proprias 117                   31            0.06
BRA_Sup ODC 21                                   31            0.06
BRA_Loja Shopping Interlagos                     31            0.06
BRA_Loja Barra Shopping II                       31            0.06
BRA_Loja Leblon                                  31            0.06
BRA_LOJA SHOP IGUATEMI                           31            0.06
BRA_Ger Inside Sales Massivo                     31            0.06
BRA_Ger Sr Dev E-care B2C                        30            0.06
BRA_Sup Atend COE - Curitiba 11                  30            0.06
BRA_Sup Instal B2B - CSC                         30            0.06
BRA_Sup Operacoes Proprias 45                    30            0.06
BRA_Sup Operacoes Proprias 108                   30            0.06
BRA_Loja Manauara Shopping                       30            0.06
BRA_Coord Dev Contact Center                     29            0.06
BRA_Coord Imp Tx/AC                              29            0.06
BRA_Coord O&M E Suporte Transmissao Nac          29            0.06
BRA_Sup Instal Sul 053                           29            0.06
BRA_Sup Serv Cliente - Freguesia 02_01           29            0.06
BRA_Coord Serv ao Cliente - Lapa/Jaguare         29            0.06
BRA_SUP OPERACOES PROPRIAS 100                   29            0.06
BRA_Sup Operacoes Proprias 43                    29            0.06
BRA_SUP OPERACOES PROPRIAS 53                    29            0.06
BRA_Sup Operacoes Proprias 60                    29            0.06
BRA_Sup Operacoes Proprias 148                   29            0.06
BRA_Sup Operacoes Proprias157                    29            0.06
BRA_SUP OPERACOES PROPRIAS 143                   29            0.06
BRA_Sup ODC 23                                   29            0.06
BRA_Sup Operacoes Proprias 07                    29            0.06
BRA_Loja Top Shopping Iguacu                     29            0.06
BRA_Loja Jardins                                 29            0.06
BRA_LOJA SHOPPING PKS ICONICA DF                 29            0.06
BRA_Loja Goiania Shopping                        29            0.06
BRA_Ger Pos Vendas Massivo                       29            0.06
ASEGURAMIENTO DE INGRESOS Y FILIALES             28            0.06
BRA_Ger Qualid Acesso Movel Ginfo e BMK          28            0.06
BRA_Coord Serv ao Cliente - Brasilia I           28            0.06
BRA_Sup Manut Cw 030                             28            0.06
BRA_Sup Cont e Agend NE 003                      28            0.06
BRA_Sup Manut NE 006                             28            0.06
BRA_Coord Servicos ao Cliente RJ Goas 1          28            0.06
BRA_Coord Serv ao Cliente - Nova Iguacu          28            0.06
BRA_SUP OPERACOES PROPRIAS 63                    28            0.06
BRA_SUP OPERACOES PROPRIAS 77                    28            0.06
BRA_Sup Operacoes Proprias 94                    28            0.06
BRA_Sup Operacoes Proprias 41                    28            0.06
BRA_Ger Televendas 03                            28            0.06
BRA_SUP OPERACOES PROPRIAS 144                   28            0.06
BRA_Loja Shopping Analia Franco                  28            0.06
BRA_Loja Jundiai Maxi Shopping                   28            0.06
BRA_SUP RELACIONAMENTO COM CLIENTE VII           28            0.06
BRA_Loja Iguatemi Ba                             28            0.06
BRA_Loja Buriti                                  28            0.06
BRA_Loja Shopping Campo Grande                   28            0.06
BRA_Coord Projetos de Rede                       27            0.06
BRA_GER O&M TRANSMISSAO NACIONAL                 27            0.06
BRA_Coord B2B e O&M Fixa BA1                     27            0.06
BRA_Ger Serv ao Clien Rede Mov PR/SC/RS          27            0.06
BRA_Sup Instal B2B - Sul 001                     27            0.06
BRA_SUP OPERACOES PROPRIAS 73                    27            0.06
BRA_Sup Operacoes Proprias 174                   27            0.06
BRA_Sup Operacoes Proprias 122                   27            0.06
BRA_Sup Operacoes Proprias 161                   27            0.06
BRA_Sup ODC 13                                   27            0.06
BRA_Loja Ribeirao Shopping                       27            0.06
BRA_SUP SUPORTE VENDAS V                         27            0.06
BRA_Loja Savassi                                 27            0.06
BRA_Loja Shopping Salvador                       27            0.06
BRA_Loja Pantanal Cuiaba                         27            0.06
BRA_Ger Operacao Clientes Brasil                 27            0.06
BRA_Coord Representacao JT                       26            0.05
BRA_Ger Qualid CORE SVA BB-IP e Anatel           26            0.05
BRA_Ger Contrato CAPEX                           26            0.05
BRA_Ger Engenharia de Servicos de Voz            26            0.05
BRA_Ger Servicos Integracao Rede                 26            0.05
BRA_Sup Cont e Agend Cw 003                      26            0.05
BRA_Sup Manut Sul 02                             26            0.05
BRA_Sup Serv ao Cliente - Rib Preto 02           26            0.05
BRA_Coord Qualidade - Area de Ref                26            0.05
BRA_Sup Serv ao Cliente - Litoral 01_01          26            0.05
BRA_Sup Operacoes Proprias 35                    26            0.05
BRA_Sup Operacoes Proprias 88                    26            0.05
BRA_Sup Operacoes Proprias 80                    26            0.05
BRA_Sup Operacoes Proprias 67                    26            0.05
BRA_Sup Televendas 04                            26            0.05
BRA_Sup Televendas 31                            26            0.05
BRA_Sup Televendas 14                            26            0.05
BRA_Sup Operacoes Proprias 136                   26            0.05
BRA_Ger Suporte Operacoes 16                     26            0.05
BRA_Sup Operacoes Proprias 29                    26            0.05
BRA_Sup Operacoes Proprias 05                    26            0.05
BRA_Sup ODC 15                                   26            0.05
BRA_Sup Operacoes Proprias 170                   26            0.05
BRA_Loja Shopping Intern Guar                    26            0.05
BRA_Loja Metropole                               26            0.05
BRA_Loja Dom Pedro                               26            0.05
BRA_Loja Rio Preto Shopping                      26            0.05
BRA_Loja Volta Redonda                           26            0.05
BRA_Loja Shopping Diamond Mall Iconica           26            0.05
BRA_Loja Rondonopolis                            26            0.05
BRA_Loja Shop Barigui                            26            0.05
BRA_Ger Inbound Fixa e Movel                     26            0.05
BRA_COORD BACKOFFICE - CWB                       25            0.05
BRA_Sup Instal Cw 052                            25            0.05
BRA_Sup Manut NE 048                             25            0.05
BRA_Sup Serv Cliente - Area Ref 04               25            0.05
BRA_Sup Operacoes Proprias 42                    25            0.05
BRA_SUP OPERACOES PROPRIAS 27                    25            0.05
BRA_Sup Operacoes Proprias 70                    25            0.05
BRA_Sup Operacoes Proprias 64                    25            0.05
BRA_Sup Operacoes Proprias 138                   25            0.05
BRA_Sup Operacoes Proprias 125                   25            0.05
BRA_Sup Operacoes Proprias 107                   25            0.05
BRA_SUP OPERACOES PROPRIAS 110                   25            0.05
BRA_SUP OPERACOES PROPRIAS 159                   25            0.05
BRA_Sup Operacoes Proprias 19                    25            0.05
BRA_Sup Operacoes Proprias 103                   25            0.05
BRA_Sup Operacoes Proprias 102                   25            0.05
BRA_Loja Shopping Center Norte I                 25            0.05
BRA_Loja Shopping Itaquera                       25            0.05
BRA_Loja Shopping Plaza Sul                      25            0.05
BRA_Loja Mogi Shopping Center                    25            0.05
BRA_Loja Esplanada                               25            0.05
BRA_Loja Praiamar                                25            0.05
BRA_Ger Operacoes e Atendimento VIP              25            0.05
BRA_Loja Sao Jose Do Rio Preto                   25            0.05
BRA_Loja Centro RJ                               25            0.05
BRA_Loja Shopping Midway                         25            0.05
BRA_Loja Shopping Barra                          25            0.05
BRA_Loja Estacao Cuiaba                          25            0.05
BRA_Loja Shop Mueller                            25            0.05
BRA_COORD SERVICOS RH REGIONAIS                  24            0.05
BRA_Coord Servicos Tecnicos II                   24            0.05
BRA_Coord Eventos Criticos e Projetos            24            0.05
BRA_Coord Configuracao de Servicos B2B           24            0.05
BRA_Coord Supervisao Transmissao Nac             24            0.05
BRA_Sup Atend COE - Curitiba 09                  24            0.05
BRA_Sup Atend COE - São Paulo 03                 24            0.05
BRA_Coord Atend CO - São Paulo 02                24            0.05
BRA_Sup Atend CO - São Paulo 02                  24            0.05
BRA_Sup Atend CO - São Paulo 05                  24            0.05
BRA_Sup Cont e Agend Cw 004                      24            0.05
BRA_Coord Manut Rede Externa DF/MS               24            0.05
BRA_SUP INSTAL SUL 088                           24            0.05
BRA_Sup Manut Cw 010                             24            0.05
BRA_Sup Inst Cw 023                              24            0.05
BRA_Sup Manut Cw 022                             24            0.05
BRA_Sup Instal Cw 038                            24            0.05
BRA_Sup Cont e Agend NE 002                      24            0.05
BRA_Coord Operacoes - VTA                        24            0.05
BRA_SUP MANUT SE 047                             24            0.05
BRA_Sup Serv ao Cliente - Rib Preto 01           24            0.05
BRA_Sup Serv ao Cliente - Cas/Ind 01_06          24            0.05
BRA_Sup Agendamento e Controle Fibra 5           24            0.05
BRA_Sup Agendamento e Controle Fibra 6           24            0.05
BRA_SUP SERV AO CLIENTE - JUNDIAI 01_01          24            0.05
BRA_Sup Serv Cliente - Freguesia 02_04           24            0.05
BRA_SUP OPERACOES PROPRIAS 68                    24            0.05
BRA_SUP OPERACOES PROPRIAS 76                    24            0.05
BRA_SUP OPERACOES PROPRIAS 78                    24            0.05
BRA_Sup Operacoes Proprias 32                    24            0.05
BRA_SUP OPERACOES PROPRIAS 30                    24            0.05
BRA_Sup Operacoes Proprias 92                    24            0.05
BRA_SUP OPERACOES PROPRIAS 90                    24            0.05
BRA_SUP OPERACOES PROPRIAS 93                    24            0.05
BRA_Sup Operacoes Proprias 47                    24            0.05
BRA_SUP TELEVENDAS 10                            24            0.05
BRA_Sup Televendas 38                            24            0.05
BRA_SUP OPERACOES PROPRIAS 150                   24            0.05
BRA_Sup Operacoes Proprias 127                   24            0.05
BRA_Sup Operacoes Proprias 129                   24            0.05
BRA_Sup Operacoes Proprias 111                   24            0.05
BRA_Sup Operacoes Proprias 20                    24            0.05
BRA_SUP OPERACOES PROPRIAS 147                   24            0.05
BRA_Sup ODC 18                                   24            0.05
BRA_Sup Operacoes Proprias 16                    24            0.05
BRA_Loja Iguatemi Sp                             24            0.05
BRA_Loja Shopping Center Norte Ii                24            0.05
BRA_Loja Osasco Plaza Shopping                   24            0.05
BRA_Loja Abc Plaza Shopping                      24            0.05
BRA_Loja Campinas Iguatemi                       24            0.05
BRA_Loja Bauru                                   24            0.05
BRA_Loja Minas Shopping                          24            0.05
BRA_LOJA ITAU POWER SHOPPING II                  24            0.05

 14) HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO

In [227]:
df_julio[['HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO', 'Localización País']].head(1)

   HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO Localización País
0                                            37.5            España

In [228]:
df_julio[['HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO', 'Localización País']].tail(1)

       HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO Localización País
48430                                            44.0            Brasil

15) Nombre del puesto

In [229]:
df_julio['Nombre del puesto'].unique()

<StringArray>
[           'ENCARGADO DE OPERACION',        'TITULADO SUPERIOR O MASTER',
        'OPERADOR DE COMUNICACIONES', 'TITULADO/TECNICO MEDIO O DE GRADO',
                              'STAM',         'RESPONSABLE VENTAS 1 BASE',
                    'ADMINISTRATIVO',                  'ASESOR COMERCIAL',
                   'EXPERTO NIVEL 2',                          'DIRECTOR',
 ...
    'GERENTE PROCESSOS E EFICIENCIA',  'ANALISTA PROCESSOS EFICIENCIA PL',
    'Gerente Processos e Eficiencia',    'ANALISTA ESTRATEGIA DIGITAL SR',
   'ESPECIALISTA ESTRATEGIA DIGITAL',              'Analista Projetos SR',
                'Diretor Presidente',  'SECRETARIA EXECUTIVA PRESIDENCIA',
                        'Estagiario',                        'ESTAGIARIO']
Length: 1605, dtype: str

In [230]:
# Conteo absoluto y porcentaje por puesto
conteo_puesto= df_julio['Nombre del puesto'].value_counts(dropna=False)
porcentaje_puesto=round( df_julio['Nombre del puesto'].value_counts(normalize=True, dropna=False) * 100,2)

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_puesto, 'Porcentaje (%)': porcentaje_puesto})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

                                               Cantidad  Porcentaje (%)
Nombre del puesto
OPERADOR DE COMUNICACIONES                         4049            8.36
TITULADO/TECNICO MEDIO O DE GRADO                  2552            5.27
ASESOR COMERCIAL                                   1323            2.73
TITULADO SUPERIOR O MASTER                         1221            2.52
INSTALADOR LA                                      1204            2.49
ENCARGADO DE OPERACION                             1117            2.31
CONSULTOR NEGOCIOS LOJA I 6H                       1011            2.09
Consultor Negocios Loja I                           978            2.02
REPARADOR LA                                        905            1.87
Atendente Retencao                                  848            1.75
ADMINISTRATIVO                                      762            1.57
ATENDENTE RETENCAO                                  579            1.20
COORDINADOR                                         576            1.19
JEFE                                                564            1.16
ATENDENTE DE AGENDAMENTO E CONTROLE                 548            1.13
Instalador La                                       540            1.11
ASSISTENTE TECNICO                                  527            1.09
CONSULTOR NEGOCIOS LOJA I                           515            1.06
Atendente Telemarketing                             504            1.04
ATENDENTE CO                                        448            0.93
Reparador La                                        445            0.92
ATENDENTE FIXA PLATINUM                             402            0.83
Assistente Tecnico                                  398            0.82
ASSISTENTE RELACIONAMENTO ODC                       389            0.80
Atendente Atendimento Geral                         376            0.78
ASESOR BASE                                         372            0.77
ASSISTENTE ADMINISTRATIVO                           357            0.74
Atendente Fixa Platinum                             342            0.71
Supervisor Servicos ao Cliente                      340            0.70
Consultor Relacionamento Loja                       307            0.63
ATENDENTE COE PL                                    304            0.63
RESPONSABLE VENTAS 1 SENIOR                         284            0.59
Atendente Suporte                                   279            0.58
CONSULTOR                                           274            0.57
GESTOR POSTVENTA DE CLIENTE                         247            0.51
Consultor Negocios Loja I (NOC)                     216            0.45
AUXILIAR LA                                         214            0.44
ATENDENTE SUPORTE                                   210            0.43
GERENTE                                             209            0.43
CONSULTOR RELACIONAMENTO LOJA                       205            0.42
EXPERTO NIVEL 1                                     204            0.42
GERENTE NEGOCIOS III                                199            0.41
RESPONSABLE VENTAS 4 SENIOR                         195            0.40
ANALISTA TELECOM JR                                 195            0.40
ANALISTA SISTEMAS SR                                189            0.39
RESPONSABLE VENTAS 3 SENIOR                         188            0.39
Tecnico Telecom Sr                                  187            0.39
CONSULTOR MARKETING                                 187            0.39
SUPERVISOR SERVICOS AO CLIENTE                      185            0.38
Gerente Negocios Loja I                             183            0.38
Recepcionista Loja                                  182            0.38
Tecnico Telecom Pl                                  174            0.36
GERENTE NEGOCIOS LOJA I                             171            0.35
Consultor Telecom                                   169            0.35
RESPONSABLE VENTAS 3 ENTRADA                        168            0.35
GERENTE NEGOCIOS IV                                 164            0.34
CONSULTOR SISTEMAS                                  159            0.33
RESPONSABLE VENTAS 1 MASTER                         155            0.32
ANALISTA TELECOM PL                                 155            0.32
TECNICO TELECOM PL                                  148            0.31
ATENDENTE TELEMARKETING                             148            0.31
Gerente Negocios III                                145            0.30
ANALISTA TELECOM SR                                 144            0.30
CONSULTOR PROJETOS                                  143            0.30
ATENDENTE REDES SOCIAIS                             143            0.30
RESPONSABLE VENTAS 4 BASE                           141            0.29
Gerente Negocios IV                                 138            0.28
Tecnico Telecom Jr                                  130            0.27
GERENTE NEGOCIOS V                                  126            0.26
CONSULTOR NEGOCIOS LOJA I (NOC)                     123            0.25
Consultor Tecnologico                               121            0.25
CONSULTOR TELECOM                                   120            0.25
ANALISTA MARKETING SR                               119            0.25
Gerente Contas III                                  119            0.25
EXPERTO NIVEL 2                                     117            0.24
ANALISTA PROJETOS SR                                117            0.24
Gerente Contas II                                   116            0.24
Engenheiro Telecom Sr                               115            0.24
RESPONSABLE VENTAS 4 MASTER                         114            0.24
Analista Telecom Sr                                 114            0.24
TECNICO TELECOM SR                                  112            0.23
Analista Telecom Pl                                 112            0.23
RESPONSABLE VENTAS 1 BASE                           107            0.22
Auxiliar La                                         106            0.22
Consultor Marketing                                 106            0.22
GERENTE NEGOCIOS II                                 105            0.22
ANALISTA GESTÃO DE PESSOAS SR                       104            0.21
ANALISTA SERVICO CLIENTE JR                         103            0.21
GESTOR POSTVENTA DE CLIENTE ENTRADA                 101            0.21
CONSULTOR TECNOLOGICO                               101            0.21
ATENDENTE RELACIONAMENTO ODC                        100            0.21
Gerente Geral Loja I                                100            0.21
TECNICO TELECOM JR                                   99            0.20
OPERADOR DE COMUNICACIONES (INF.GESTION)             96            0.20
TECNICO ADSL                                         95            0.20
ANALISTA SERVICO CLIENTE SR                          94            0.19
Analista Telecom Jr                                  94            0.19
Coordenador Servico ao Cliente                       94            0.19
GERENTE CONTAS III                                   92            0.19
GERENTE VENDAS B2C                                   92            0.19
RESPONSABLE VENTAS 3 MASTER                          91            0.19
Assistente Administrativo                            90            0.19
SUPERVISOR ATENDIMENTO                               90            0.19
Supervisor Rede                                      89            0.18
SUPERVISOR REDE                                      88            0.18
Atendente Fixa                                       88            0.18
GERENTE CONTAS II                                    88            0.18
ATENDENTE MOVEL                                      86            0.18
RESPONSABLE VENTAS 3 BASE                            84            0.17
Engenheiro Telecom Pl                                82            0.17
COORDENADOR SERVICO AO CLIENTE                       82            0.17
RECEPCIONISTA LOJA                                   80            0.17
ANALISTA SISTEMAS PL                                 79            0.16
Analista Suporte Comercial I                         79            0.16
ATENDENTE ATENDIMENTO GERAL                          76            0.16
Tecnico Adsl                                         75            0.15
ANALISTA SERVICO CLIENTE PL                          75            0.15
ANALISTA GESTÃO DE PESSOAS PL                        74            0.15
CONSULTOR PLANEJAMENTO COMERCIAL                     72            0.15
GERENTE GERAL LOJA I                                 72            0.15
GERENTE NEGOCIOS LOJA                                70            0.14
ANALISTA SUPORTE VENDAS PL                           70            0.14
DELINEANTES/OPER.AUDIOV.                             68            0.14
Gerente Marketing                                    67            0.14
Gerente Negocios II                                  67            0.14
Fiscal Telecom                                       65            0.13
CONSULTOR PRE VENDAS IV                              65            0.13
Analista Sistemas Sr                                 63            0.13
CONSULTOR GESTÃO DE PESSOAS                          62            0.13
Analista Marketing Sr                                62            0.13
ANALISTA LOGISTICA PL                                62            0.13
Gerente Vendas                                       62            0.13
ANALISTA MARKETING PL                                61            0.13
ANALISTA PROCESSOS SR                                60            0.12
ATENDENTE MOVEL TOP                                  60            0.12
IBERBANDA                                            59            0.12
CONSULTOR PLANEJAMENTO E CONTROLE                    58            0.12
ASSISTENTE OUVIDORIA                                 57            0.12
Ligador Dg                                           56            0.12
Atendente Telemarketing Ativo                        56            0.12
ANALISTA SUPORTE VENDAS SR                           56            0.12
SUPERVISOR RETENCAO                                  55            0.11
CONSULTOR SUPORTE VENDAS                             55            0.11
ANALISTA PLANEJAMENTO COMERCIAL SR                   54            0.11
ANALISTA PLANEJAMENTO E CONTROLE SR                  52            0.11
CONSULTOR NEGOCIOS PREMIUM 6H                        52            0.11
ANALISTA SUPORTE VENDAS JR                           52            0.11
DIRECTOR                                             51            0.11
CONSULTOR INOVACAO DIGITAL                           51            0.11
COORDENADOR TELECOM                                  51            0.11
Analista Sistemas Pl                                 50            0.10
ANALISTA RELACIONAMENTO COM CLIENTE SR               50            0.10
ENCARGADO DE GESTION                                 49            0.10
ANALISTA SUPORTE COMERCIAL I                         49            0.10
STAM                                                 48            0.10
ANALISTA MONITORIA                                   48            0.10
TECNICO SUPERIOR                                     47            0.10
Analista Servico Cliente Pl                          47            0.10
Consultor Planejamento e Controle                    46            0.09
ENGENHEIRO TELECOM SR                                46            0.09
Atendente Movel VIP                                  46            0.09
Analista Suporte Comercial I (OC)                    46            0.09
ANALISTA PROCESSOS PL                                45            0.09
ANALISTA SUPORTE OPERACAO SR                         45            0.09
Analista Servico Cliente Jr                          45            0.09
CONSULTOR RELACIONAMENTO COM CLIENTE                 45            0.09
GERENTE VENDAS                                       45            0.09
GERENTE CONTAS I                                     45            0.09
RESPONSABLE VENTAS 2 BASE                            44            0.09
ANALISTA GESTÃO DE PESSOAS JR                        44            0.09
ANALISTA PROCESSOS JR                                44            0.09
ATENDENTE COE SR                                     44            0.09
FISCAL TELECOM                                       44            0.09
SECRETARIAS DIRECCION                                43            0.09
Coordenador Telecom                                  43            0.09
ANALISTA SUPORTE OPERACAO PL                         43            0.09
Gerente Negocios V                                   43            0.09
Consultor Sistemas                                   42            0.09
Analista Suporte Vendas Pl                           42            0.09
ANALISTA PROJETOS PL                                 41            0.08
ANALISTA INOVACAO DIGITAL SR                         41            0.08
ATENDENTE FIXA                                       41            0.08
Atendente Atend Cliente Empresarial                  41            0.08
Gerente Geral Loja II                                41            0.08
Analista Suporte Vendas Jr                           41            0.08
JPyC N2                                              40            0.08
ANALISTA SUPORTE SR                                  40            0.08
Instalador La Pl                                     40            0.08
ANALISTA LOGISTICA JR                                40            0.08
GERENTE CONTAS IV                                    40            0.08
Analista Suporte Vendas Sr                           40            0.08
GERENTE MARKETING                                    39            0.08
TTP                                                  38            0.08
CONSULTOR SUPORTE OPERACAO                           38            0.08
TECNICO GOAS                                         38            0.08
ATENDENTE ATEND CLIENTE EMPRESARIAL                  38            0.08
Analista Suporte Comercial II                        38            0.08
V-3                                                  37            0.08
Analista Processos Sigilo Jr                         37            0.08
CONSULTOR NEGOCIOS PREMIUM                           37            0.08
CONSULTOR PRODUTOS                                   37            0.08
RESPONSABLE VENTAS 1 EXECUTIVE                       36            0.07
Consultor Projetos                                   36            0.07
CONSULTOR PROCESSOS                                  36            0.07
Gerente Contas I                                     36            0.07
Consultor Vendas                                     36            0.07
ENGENHEIRO TELECOM PL                                35            0.07
Consultor Planejamento Comercial                     35            0.07
ANALISTA LOGISTICA SR                                35            0.07
GERENTE GERAL LOJA II                                35            0.07
Atendente Suporte Vendas                             35            0.07
Analista Prevencao Fraude Jr                         34            0.07
INSTRUTOR TREINAMENTO                                34            0.07
ANALISTA SISTEMAS JR                                 34            0.07
GER SR MARKETING                                     34            0.07
Atendente Movel TOP                                  34            0.07
CONSULTOR GESTAO VENDAS                              34            0.07
Analista Monitoria                                   33            0.07
CONSULTOR EXPERIENCIA CLIENTE                        33            0.07
ATENDENTE TELEMARKETING ATIVO                        33            0.07
Atendente Retencao Vendas                            33            0.07
GER SR VENDAS                                        33            0.07
TRAINEE                                              32            0.07
ANALISTA SUPORTE OPERACAO JR                         32            0.07
Consultor Negocios Premium                           31            0.06
GERENTE RELAC POS VENDAS I                           31            0.06
Gerente Servico ao Cliente                           30            0.06
INSTALADOR LA PL                                     30            0.06
ANALISTA RELACIONAMENTO COM CLIENTE PL               30            0.06
SUPERVISOR TELEVENDAS                                30            0.06
Assistente Relacionamento ODC                        30            0.06
Analista Logistica Pl                                30            0.06
GER SR TERRITORIAL                                   30            0.06
GERENTE RELAC POS VENDAS II                          30            0.06
RESPONSABLE VENTAS 2 SENIOR                          29            0.06
ANALISTA PLANEJAMENTO E CONTROLE JR                  29            0.06
Especialista Telecom                                 29            0.06
GERENTE SERVICO AO CLIENTE                           29            0.06
Analista Servico Cliente Sr                          29            0.06
Consultor Negócios B2B                               29            0.06
GERENTE NEGOCIOS I                                   29            0.06
Analista Projetos Sr                                 28            0.06
ESPECIALISTA TELECOM                                 28            0.06
TECNICO TELECOM III                                  28            0.06
Tecnico GOAS                                         28            0.06
ATENDENTE MOVEL VIP                                  28            0.06
Consultor Gestao Vendas                              28            0.06
Gerente Contas IV                                    28            0.06
Consultor Pre Vendas IV                              28            0.06
ANALISTA PLANEJAMENTO E CONTROLE PL                  27            0.06
ANALISTA PREVENCAO FRAUDE JR                         27            0.06
Consultor Suporte Vendas                             27            0.06
GERENTE RELAC POS VENDAS III                         27            0.06
GERENTE SISTEMAS                                     26            0.05
ANALISTA QUALIDADE SISTEMAS SR                       26            0.05
ANALISTA PRODUCAO TI SR                              26            0.05
SUPERVISOR RELACIONAMENTO ODC                        26            0.05
C-4                                                  25            0.05
Analista Fiscal Jr                                   25            0.05
COORDENADOR GESTÃO DE PESSOAS                        25            0.05
CONSULTOR SERVICO AO CLIENTE                         25            0.05
ANALISTA CANAIS DIGITAIS SR                          25            0.05
ANALISTA PLANEJAMENTO COMERCIAL PL                   25            0.05
ESPECIALISTA SISTEMAS                                24            0.05
Tecnico Projeto Pl                                   24            0.05
Analista Marketing Pl                                24            0.05
CONSULTOR CANAIS                                     24            0.05
CONSULTOR PLANEJAMENTO MARKETING                     24            0.05
ANALISTA GESTAO VENDAS SR                            24            0.05
ANALISTA SUPORTE COMERCIAL I (OC)                    24            0.05
CONSULTOR NEGOCIOS LOJA 8H                           24            0.05
Analista Planejamento e Controle Sr                  23            0.05
CONSULTOR CONTROLE OPER FINANCEIRAS                  23            0.05
Analista Suporte Sistemas Jr                         23            0.05
TECNICO CADASTRO JR                                  23            0.05
Supervisor Atendimento Operacoes                     23            0.05

15)   Nacionalidad

In [231]:
df_julio['Nacionalidad'].unique()

<StringArray>
['ESPAÑOLA', nan]
Length: 2, dtype: str

In [232]:
df_julio['Nacionalidad'].value_counts()
# solo hay 16019

Nacionalidad
ESPAÑOLA    16019
Name: count, dtype: int64

In [233]:
df_julio['Nacionalidad'].isna().sum()
#nulos

np.int64(32412)

In [234]:
df_julio['Nacionalidad'].info()# deberia tener 48431

<class 'pandas.Series'>
RangeIndex: 48431 entries, 0 to 48430
Series name: Nacionalidad
Non-Null Count  Dtype
--------------  -----
16019 non-null  str
dtypes: str(1)
memory usage: 378.5 KB

In [235]:
# se puede sacar por la columna ocaluzacion Pais si damos por echo que todos los que trabajan en brasil son nacionalizado brasileños

 17) Estado de empleado

In [236]:
df_julio['Estado de empleado'].unique()

<StringArray>
['Activo']
Length: 1, dtype: str

18) PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES

In [237]:
df_julio['PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES'].unique()

array([37.5, 32.8, 34.5, 20. , 29.6, 25. , 36.5, 36. ,  0.4, 35.5, 35. ,
       34.3, 33.6, 33.3, 37. , 29.4, 22.5, 34. , 33.5, 33. , 36.7, 33.8,
       19.7, 18.8, 26.6,  1.5, 24.7, 37.3, 27. , 22.3, 35.4, 28.2, 24.6,
       28. , 28.4, 40. , 44. , 30. ])

In [238]:
# Conteo absoluto y porcentaje por horas
conteo_horas= df_julio['PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES'].value_counts(dropna=False)
porcentaje_horas=round( df_julio['PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES'].value_counts(normalize=True, dropna=False) * 100,2)

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_horas, 'Porcentaje (%)': porcentaje_horas})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

                                                   Cantidad  Porcentaje (%)
PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES
40.0                                                  16369           33.80
37.5                                                  15556           32.12
44.0                                                   9249           19.10
36.0                                                   6802           14.04
32.8                                                    146            0.30
34.5                                                     63            0.13
25.0                                                     44            0.09
35.0                                                     39            0.08
34.3                                                     34            0.07
36.5                                                     17            0.04
37.0                                                     17            0.04
20.0                                                     15            0.03
33.6                                                     14            0.03
29.6                                                     13            0.03
35.5                                                      8            0.02
22.5                                                      6            0.01
24.7                                                      5            0.01
29.4                                                      4            0.01
0.4                                                       3            0.01
34.0                                                      3            0.01
18.8                                                      3            0.01
1.5                                                       2            0.00
35.4                                                      2            0.00
24.6                                                      2            0.00
30.0                                                      2            0.00
33.3                                                      1            0.00
33.5                                                      1            0.00
33.0                                                      1            0.00
36.7                                                      1            0.00
33.8                                                      1            0.00
19.7                                                      1            0.00
26.6                                                      1            0.00
37.3                                                      1            0.00
27.0                                                      1            0.00
22.3                                                      1            0.00
28.2                                                      1            0.00
28.0                                                      1            0.00
28.4                                                      1            0.00

19) Fecha de Nacimiento

In [239]:
df_julio['Fecha de Nacimiento'].head()

0   1954-09-08
1   1952-02-12
2   1954-06-07
3   1956-06-04
4   1966-12-01
Name: Fecha de Nacimiento, dtype: datetime64[us]

20) 'Clase de empleado'

In [240]:
df_julio['Clase de empleado'].unique()

<StringArray>
['EMP', 'INP', 'PRA']
Length: 3, dtype: str

In [241]:
# Conteo absoluto y porcentaje por clase empleado
conteo_clase= df_julio['Clase de empleado'].value_counts(dropna=False)
porcentaje_clase=round( df_julio['Clase de empleado'].value_counts(normalize=True, dropna=False) * 100,2)

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_clase, 'Porcentaje (%)': porcentaje_clase})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

                   Cantidad  Porcentaje (%)
Clase de empleado
EMP                   48420           99.98
PRA                       8            0.02
INP                       3            0.01

21) Discapacidad

In [242]:
df_julio['Discapacidad'].unique()

<StringArray>
['No', 'Sí']
Length: 2, dtype: str

In [243]:
# Conteo absoluto y porcentaje por clase empleado
conteo_discapacidad= df_julio['Discapacidad'].value_counts(dropna=False)
porcentaje_discapacidad=round( df_julio['Discapacidad'].value_counts(normalize=True, dropna=False) * 100,2)

# Creamos un DataFrame resumen
df_areas = pd.DataFrame({'Cantidad': conteo_discapacidad, 'Porcentaje (%)': porcentaje_discapacidad})

# Mostramos todas las filas sin truncar
pd.set_option('display.max_rows', None)
print(df_areas)

              Cantidad  Porcentaje (%)
Discapacidad
No               47978           99.06
Sí                 453            0.94

22) Fecha de Alta

In [244]:
df_julio['Fecha de Alta'].head()

0   1978-12-21
1   1979-07-13
2   1981-12-01
3   1981-12-01
4   1986-12-15
Name: Fecha de Alta, dtype: datetime64[us]

23) ID persona

In [245]:
df_julio['ID persona'].head()

0    Persona 1716852
1    Persona 1716853
2    Persona 1716854
3    Persona 1716855
4    Persona 1716856
Name: ID persona, dtype: str

In [246]:
df_julio['ID persona'].min()

'Persona 1403121'

In [247]:
df_julio['ID persona'].max()

'Persona 1732870'

# ARCHIVO DF_BAJAS 
se refiere a bajas de agosto

In [248]:
df_bajas.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID persona              360 non-null    str
 1   Unidad de Negocio       360 non-null    str
 2   COD. UNIDAD DE NEGOCIO  360 non-null    int64
 3   Subactividad_desc       360 non-null    str
 4   Subactividad            360 non-null    str
 5   Genero                  360 non-null    str
 6   Fecha nacimiento        360 non-null    datetime64[us]
 7   Fecha fin de contrato   360 non-null    datetime64[us]
 8   Tipo de baja local      360 non-null    str
 9   Clase de empleado       360 non-null    str
 10  Tipo de baja global     360 non-null    str
 11  Nombre del puesto       360 non-null    str
dtypes: datetime64[us](2), int64(1), str(9)
memory usage: 33.9 KB

0) ID person

In [249]:
df_bajas['ID persona'].head()

0    Persona 1716855
1    Persona 1716863
2    Persona 1716872
3    Persona 1716873
4    Persona 1716956
Name: ID persona, dtype: str

1) Unidad de negocio

In [250]:
df_bajas['Unidad de Negocio'].unique()

<StringArray>
['España', 'Brasil']
Length: 2, dtype: str

In [251]:
#importamos la funciones_analisis
from scr.funciones_analisis import analizar_columna

In [252]:
analizar_columna(df_bajas,'Unidad de Negocio')

                   Cantidad  Porcentaje (%)
Unidad de Negocio
Brasil                  354           98.33
España                    6            1.67

2) COD. UNIDAD DE NEGOCIO

In [253]:
df_bajas['COD. UNIDAD DE NEGOCIO'].unique()

array([156, 185])

In [254]:
analizar_columna(df_bajas,'COD. UNIDAD DE NEGOCIO')

                        Cantidad  Porcentaje (%)
COD. UNIDAD DE NEGOCIO
185                          354           98.33
156                            6            1.67

3) Subactividad_desc

In [255]:
df_bajas['Subactividad_desc'].unique()

<StringArray>
[                              'tecnologíayplanificación',
                                      'gestionydireccion',
                                   'vigilanciayseguridad',
                                 'intervenciónyauditoria',
                      'tesoreríayplanificaciónfinanciera',
                                           'contabilidad',
                              'planificaciónycontrolling',
                                       'gestióndeseguros',
                                  'relaciónconinversores',
                                                'compras',
                               'gestiónfiscalytributaria',
                       'gestiónymantenimientodeedificios',
                         'administraciónygestióndecobros',
                           'gestióndelamorosidadeimpagos',
                                     'mercadodecapitales',
                                            'facturación',
                         'calidadyoptimizacióndeprocesos',
                'aseguramientodeingresosycontroldefraude',
                   'organización,planificaciónyreporting',
                   'relacioneslaboralesygestióndealiados',
                              'restodeserviciosgenerales',
                'compensación,beneficiosymovilidadglobal',
                                     'talentoydesarrollo',
                                              'formación',
                                              'selección',
                          'asesoríalegalysoportejurídico',
                    'relacionescongobiernoeinstituciones',
                                           'producciónit',
                                       'supervisióndered',
                                         'operacióndered',
                                'aplicaciones/desarrollo',
 'ingenieríayconstruccióndeinfraestructurasdereddeacceso',
                    'mantenimientoredtroncal(redinterna)',
                                      'callcentertécnico',
                                  'fuerzadeventasdirecta',
                                          'soporteventas',
                               'canaltelefónico-atención']
Length: 37, dtype: str

In [256]:
analizar_columna(df_bajas,'Subactividad_desc')

                                                    Cantidad  Porcentaje (%)
Subactividad_desc
callcentertécnico                                         97           26.94
canaltelefónico-atención                                  35            9.72
supervisióndered                                          32            8.89
gestióndelamorosidadeimpagos                              19            5.28
fuerzadeventasdirecta                                     17            4.72
operacióndered                                            14            3.89
producciónit                                              12            3.33
planificaciónycontrolling                                 11            3.06
relacioneslaboralesygestióndealiados                      11            3.06
selección                                                 10            2.78
contabilidad                                               9            2.50
gestióndeseguros                                           9            2.50
formación                                                  7            1.94
administraciónygestióndecobros                             6            1.67
ingenieríayconstruccióndeinfraestructurasderedd...         6            1.67
intervenciónyauditoria                                     5            1.39
compensación,beneficiosymovilidadglobal                    5            1.39
talentoydesarrollo                                         5            1.39
tecnologíayplanificación                                   4            1.11
tesoreríayplanificaciónfinanciera                          4            1.11
relaciónconinversores                                      4            1.11
restodeserviciosgenerales                                  4            1.11
relacionescongobiernoeinstituciones                        4            1.11
compras                                                    3            0.83
gestiónfiscalytributaria                                   3            0.83
facturación                                                3            0.83
calidadyoptimizacióndeprocesos                             3            0.83
aseguramientodeingresosycontroldefraude                    3            0.83
aplicaciones/desarrollo                                    3            0.83
vigilanciayseguridad                                       2            0.56
gestiónymantenimientodeedificios                           2            0.56
mercadodecapitales                                         2            0.56
asesoríalegalysoportejurídico                              2            0.56
gestionydireccion                                          1            0.28
organización,planificaciónyreporting                       1            0.28
mantenimientoredtroncal(redinterna)                        1            0.28
soporteventas                                              1            0.28

4)  Subactividad

In [257]:
df_bajas['Subactividad']

0                             Tecnología y Planificación
1                                    Gestión y Direccion
2                                 Vigilancia y Seguridad
3                                 Vigilancia y Seguridad
4                             Tecnología y Planificación
5                             Tecnología y Planificación
6                               Intervención y Auditoria
7                               Intervención y Auditoria
8                               Intervención y Auditoria
9                   Tesorería y planificación financiera
10                                          Contabilidad
11                                          Contabilidad
12                           Planificación y controlling
13                           Planificación y controlling
14                           Planificación y controlling
15                                          Contabilidad
16                                          Contabilidad
17                                          Contabilidad
18                                          Contabilidad
19                                    Gestión de Seguros
20                                    Gestión de Seguros
21                               Relación con Inversores
22                               Relación con Inversores
23                               Relación con Inversores
24                               Relación con Inversores
25                                               Compras
26                                               Compras
27                                               Compras
28                           Gestión fiscal y tributaria
29                           Gestión fiscal y tributaria
30                           Gestión fiscal y tributaria
31                  Gestión y mantenimiento de edificios
32                  Gestión y mantenimiento de edificios
33                           Planificación y controlling
34                           Planificación y controlling
35                                          Contabilidad
36                                          Contabilidad
37                                          Contabilidad
38                           Planificación y controlling
39                                    Gestión de Seguros
40                                    Gestión de Seguros
41                                    Gestión de Seguros
42                                    Gestión de Seguros
43                                    Gestión de Seguros
44                                    Gestión de Seguros
45                                    Gestión de Seguros
46                           Planificación y controlling
47                           Planificación y controlling
48                  Tesorería y planificación financiera
49                  Tesorería y planificación financiera
50                  Tesorería y planificación financiera
51                    Administración y gestión de cobros
52                    Administración y gestión de cobros
53                    Administración y gestión de cobros
54                     Gestión de la morosidad e Impagos
55                     Gestión de la morosidad e Impagos
56                                  Mercado de Capitales
57                                  Mercado de Capitales
58                           Planificación y controlling
59                           Planificación y controlling
60                           Planificación y controlling
61                     Gestión de la morosidad e Impagos
62                     Gestión de la morosidad e Impagos
63                     Gestión de la morosidad e Impagos
64                     Gestión de la morosidad e Impagos
65                     Gestión de la morosidad e Impagos
66                     Gestión de la morosidad e Impagos
67                     Gestión de la morosidad e Impagos
68                     Gestión de la morosidad e Impagos
69                     Gestión de la morosidad e Impagos
70                     Gestión de la morosidad e Impagos
71                     Gestión de la morosidad e Impagos
72                     Gestión de la morosidad e Impagos
73                     Gestión de la morosidad e Impagos
74                     Gestión de la morosidad e Impagos
75                     Gestión de la morosidad e Impagos
76                     Gestión de la morosidad e Impagos
77                     Gestión de la morosidad e Impagos
78                    Administración y gestión de cobros
79                    Administración y gestión de cobros
80                                           Facturación
81                                           Facturación
82                                           Facturación
83                    Calidad y Optimización de procesos
84                    Administración y gestión de cobros
85         Aseguramiento de ingresos y control de fraude
86         Aseguramiento de ingresos y control de fraude
87         Aseguramiento de ingresos y control de fraude
88               Organización, Planificación y Reporting
89             Relaciones Laborales y Gestión de Aliados
90                          Resto de servicios generales
91                          Resto de servicios generales
92                          Resto de servicios generales
93                          Resto de servicios generales
94             Relaciones Laborales y Gestión de Aliados
95             Relaciones Laborales y Gestión de Aliados
96             Relaciones Laborales y Gestión de Aliados
97             Relaciones Laborales y Gestión de Aliados
98             Relaciones Laborales y Gestión de Aliados
99             Relaciones Laborales y Gestión de Aliados
100            Relaciones Laborales y Gestión de Aliados
101            Relaciones Laborales y Gestión de Aliados
102          Compensación, Beneficios y Movilidad Global
103          Compensación, Beneficios y Movilidad Global
104            Relaciones Laborales y Gestión de Aliados
105            Relaciones Laborales y Gestión de Aliados
106          Compensación, Beneficios y Movilidad Global
107          Compensación, Beneficios y Movilidad Global
108          Compensación, Beneficios y Movilidad Global
109                                 Talento y Desarrollo
110                                            Formación
111                                            Formación
112                                            Formación
113                                            Formación
114                                            Formación
115                                            Formación
116                                            Formación
117                                 Talento y Desarrollo
118                                 Talento y Desarrollo
119                                 Talento y Desarrollo
120                                 Talento y Desarrollo
121                                            Selección
122                                            Selección
123                                            Selección
124                                            Selección
125                                            Selección
126                                            Selección
127                                            Selección
128                                            Selección
129                                            Selección
130                                            Selección
131                    Asesoría legal y soporte jurídico
132                    Asesoría legal y soporte jurídico
133                             Intervención y Auditoria
134                             Intervención y Auditoria
135              Relaciones con gobierno e instituciones
136              Relaciones con gobierno e instituciones
137              Relaciones con gobierno e instituciones
138              Relaciones con gobierno e instituciones
139                                        Producción IT
140                                        Producción IT
141                                        Producción IT
142                                        Producción IT
143                                        Producción IT
144                                        Producción IT
145                                        Producción IT
146                                        Producción IT
147                                        Producción IT
148                                        Producción IT
149                                        Producción IT
150                                        Producción IT
151                   Calidad y Optimización de procesos
152                   Calidad y Optimización de procesos
153                                   Supervisión de red
154                                   Supervisión de red
155                                   Supervisión de red
156                                   Supervisión de red
157                                   Supervisión de red
158                                   Supervisión de red
159                                   Supervisión de red
160                                   Supervisión de red
161                                   Supervisión de red
162                                   Supervisión de red
163                                   Supervisión de red
164                                   Supervisión de red
165                                   Supervisión de red
166                                   Supervisión de red
167                                   Supervisión de red
168                                   Supervisión de red
169                                   Supervisión de red
170                                   Supervisión de red
171                                   Supervisión de red
172                                   Supervisión de red
173                                   Supervisión de red
174                                   Supervisión de red
175                                   Supervisión de red
176                                   Supervisión de red
177                                   Supervisión de red
178                                   Supervisión de red
179                                   Supervisión de red
180                                   Supervisión de red
181                                   Supervisión de red
182                                   Supervisión de red
183                                   Supervisión de red
184                                   Supervisión de red
185                                     Operación de red
186                                     Operación de red
187                                     Operación de red
188                                     Operación de red
189                                     Operación de red
190                                     Operación de red
191                                     Operación de red
192                                     Operación de red
193                                     Operación de red
194                                     Operación de red
195                                     Operación de red
196                                     Operación de red
197                                     Operación de red
198                                     Operación de red
199                           Tecnología y Planificación
200                              Aplicaciones/Desarrollo
201                              Aplicaciones/Desarrollo
202                              Aplicaciones/Desarrollo
203    Ingeniería y construcción de infraestructuras ...
204    Ingeniería y construcción de infraestructuras ...
205    Ingeniería y construcción de infraestructuras ...
206    Ingeniería y construcción de infraestructuras ...
207    Ingeniería y construcción de infraestructuras ...
208    Ingeniería y construcción de infraestructuras ...
209              Mantenimiento Red Troncal (Red Interna)
210                                  Call Center técnico
211                                  Call Center técnico
212                                  Call Center técnico
213                                  Call Center técnico
214                                  Call Center técnico
215                                  Call Center técnico
216                                  Call Center técnico
217                                  Call Center técnico
218                                  Call Center técnico
219                                  Call Center técnico
220                                  Call Center técnico
221                                  Call Center técnico
222                                  Call Center técnico
223                                  Call Center técnico
224                                  Call Center técnico
225                                  Call Center técnico
226                                  Call Center técnico
227                                  Call Center técnico
228                                  Call Center técnico
229                                  Call Center técnico
230                                  Call Center técnico
231                                  Call Center técnico
232                                  Call Center técnico
233                                  Call Center técnico
234                                  Call Center técnico
235                                  Call Center técnico
236                                  Call Center técnico
237                                  Call Center técnico
238                                  Call Center técnico
239                                  Call Center técnico
240                                  Call Center técnico
241                                  Call Center técnico
242                                  Call Center técnico
243                                  Call Center técnico
244                                  Call Center técnico
245                                  Call Center técnico
246                                  Call Center técnico
247                                  Call Center técnico
248                                  Call Center técnico
249                                  Call Center técnico
250                                  Call Center técnico
251                                  Call Center técnico
252                                  Call Center técnico
253                                  Call Center técnico
254                                  Call Center técnico
255                                  Call Center técnico
256                                  Call Center técnico
257                                  Call Center técnico
258                                  Call Center técnico
259                                  Call Center técnico
260                                  Call Center técnico
261                                  Call Center técnico
262                                  Call Center técnico
263                                  Call Center técnico
264                                  Call Center técnico
265                                  Call Center técnico
266                                  Call Center técnico
267                                  Call Center técnico
268                                  Call Center técnico
269                                  Call Center técnico
270                                  Call Center técnico
271                                  Call Center técnico
272                                  Call Center técnico
273                                  Call Center técnico
274                                  Call Center técnico
275                                  Call Center técnico
276                                  Call Center técnico
277                                  Call Center técnico
278                                  Call Center técnico
279                                  Call Center técnico
280                                  Call Center técnico
281                                  Call Center técnico
282                                  Call Center técnico
283                                  Call Center técnico
284                                  Call Center técnico
285                                  Call Center técnico
286                                  Call Center técnico
287                                  Call Center técnico
288                                  Call Center técnico
289                                  Call Center técnico
290                                  Call Center técnico
291                                  Call Center técnico
292                                  Call Center técnico
293                                  Call Center técnico
294                                  Call Center técnico
295                                  Call Center técnico
296                                  Call Center técnico
297                                  Call Center técnico
298                                  Call Center técnico
299                                  Call Center técnico
300                                  Call Center técnico
301                                  Call Center técnico
302                                  Call Center técnico
303                                  Call Center técnico
304                                  Call Center técnico
305                                  Call Center técnico
306                                  Call Center técnico
307                             Fuerza de ventas directa
308                             Fuerza de ventas directa
309                             Fuerza de ventas directa
310                             Fuerza de ventas directa
311                             Fuerza de ventas directa
312                             Fuerza de ventas directa
313                             Fuerza de ventas directa
314                             Fuerza de ventas directa
315                             Fuerza de ventas directa
316                             Fuerza de ventas directa
317                             Fuerza de ventas directa
318                             Fuerza de ventas directa
319                             Fuerza de ventas directa
320                             Fuerza de ventas directa
321                             Fuerza de ventas directa
322                             Fuerza de ventas directa
323                             Fuerza de ventas directa
324                                       Soporte ventas
325                          Canal telefónico - Atención
326                          Canal telefónico - Atención
327                          Canal telefónico - Atención
328                          Canal telefónico - Atención
329                          Canal telefónico - Atención
330                          Canal telefónico - Atención
331                          Canal telefónico - Atención
332                          Canal telefónico - Atención
333                          Canal telefónico - Atención
334                          Canal telefónico - Atención
335                          Canal telefónico - Atención
336                          Canal telefónico - Atención
337                          Canal telefónico - Atención
338                          Canal telefónico - Atención
339                          Canal telefónico - Atención
340                          Canal telefónico - Atención
341                          Canal telefónico - Atención
342                          Canal telefónico - Atención
343                          Canal telefónico - Atención
344                          Canal telefónico - Atención
345                          Canal telefónico - Atención
346                          Canal telefónico - Atención
347                          Canal telefónico - Atención
348                          Canal telefónico - Atención
349                          Canal telefónico - Atención

In [258]:
analizar_columna(df_bajas,'Subactividad')

                                                    Cantidad  Porcentaje (%)
Subactividad
Call Center técnico                                       97           26.94
Canal telefónico - Atención                               35            9.72
Supervisión de red                                        32            8.89
Gestión de la morosidad e Impagos                         19            5.28
Fuerza de ventas directa                                  17            4.72
Operación de red                                          14            3.89
Producción IT                                             12            3.33
Planificación y controlling                               11            3.06
Relaciones Laborales y Gestión de Aliados                 11            3.06
Selección                                                 10            2.78
Contabilidad                                               9            2.50
Gestión de Seguros                                         9            2.50
Formación                                                  7            1.94
Administración y gestión de cobros                         6            1.67
Ingeniería y construcción de infraestructuras d...         6            1.67
Intervención y Auditoria                                   5            1.39
Compensación, Beneficios y Movilidad Global                5            1.39
Talento y Desarrollo                                       5            1.39
Tecnología y Planificación                                 4            1.11
Tesorería y planificación financiera                       4            1.11
Relación con Inversores                                    4            1.11
Resto de servicios generales                               4            1.11
Relaciones con gobierno e instituciones                    4            1.11
Compras                                                    3            0.83
Gestión fiscal y tributaria                                3            0.83
Facturación                                                3            0.83
Calidad y Optimización de procesos                         3            0.83
Aseguramiento de ingresos y control de fraude              3            0.83
Aplicaciones/Desarrollo                                    3            0.83
Vigilancia y Seguridad                                     2            0.56
Gestión y mantenimiento de edificios                       2            0.56
Mercado de Capitales                                       2            0.56
Asesoría legal y soporte jurídico                          2            0.56
Gestión y Direccion                                        1            0.28
Organización, Planificación y Reporting                    1            0.28
Mantenimiento Red Troncal (Red Interna)                    1            0.28
Soporte ventas                                             1            0.28

5) Genero

In [259]:
df_bajas['Genero'].unique()

<StringArray>
['M', 'F']
Length: 2, dtype: str

In [260]:
analizar_columna(df_bajas,'Genero')

        Cantidad  Porcentaje (%)
Genero
M            210           58.33
F            150           41.67

6) Fecha nacimiento

In [261]:
df_bajas['Fecha nacimiento']

0     1952-02-12
1     1952-02-12
2     1989-09-14
3     1988-09-06
4     1966-12-01
5     1980-02-13
6     1986-01-28
7     1995-08-12
8     1985-06-04
9     1992-02-20
10    1976-07-02
11    1992-01-12
12    1988-04-01
13    1978-08-21
14    1985-01-06
15    1984-08-26
16    1987-09-15
17    1995-02-15
18    1982-08-16
19    1959-08-25
20    1994-10-21
21    1985-12-01
22    1975-04-09
23    1991-09-21
24    1991-01-21
25    1997-05-09
26    1995-05-21
27    1971-03-08
28    1998-09-23
29    1991-07-19
30    1989-09-13
31    1990-10-18
32    1988-02-06
33    1988-11-28
34    1989-03-09
35    1968-12-16
36    1978-07-31
37    1992-10-28
38    1991-09-09
39    1988-04-20
40    1999-03-05
41    1983-10-29
42    1981-05-14
43    1982-05-05
44    1985-06-20
45    1994-12-10
46    1975-12-04
47    1977-07-21
48    1988-08-28
49    1964-04-25
50    1981-11-27
51    1992-08-21
52    1981-10-05
53    1983-11-02
54    1986-06-30
55    1995-06-12
56    1983-07-19
57    1987-03-16
58    1981-02-12
59    1982-03-16
60    1981-12-01
61    1995-06-08
62    1993-03-15
63    1982-05-24
64    1986-11-19
65    1983-09-07
66    1982-07-08
67    1967-11-28
68    1989-02-03
69    1975-05-04
70    1994-02-03
71    1981-02-22
72    1993-04-16
73    1994-03-25
74    1985-09-23
75    1976-12-10
76    1985-12-16
77    1991-04-07
78    1981-12-27
79    1982-02-13
80    1983-07-05
81    1973-08-01
82    1981-07-21
83    1983-02-11
84    1983-08-03
85    1994-09-26
86    1994-09-16
87    1985-10-27
88    1988-09-23
89    1996-10-27
90    1986-03-26
91    1976-10-25
92    1990-09-20
93    1988-05-10
94    1974-10-17
95    1968-02-29
96    1992-03-31
97    1996-03-07
98    1984-02-08
99    1983-07-13
100   1985-04-18
101   1978-10-03
102   1979-12-04
103   1987-09-24
104   1983-03-20
105   1975-02-23
106   1997-03-17
107   1992-09-01
108   1997-05-15
109   1989-02-20
110   1982-12-16
111   1986-07-03
112   1980-06-29
113   1981-09-13
114   1975-09-07
115   1984-08-25
116   1997-06-18
117   1992-01-25
118   1998-02-02
119   1984-06-01
120   1994-08-03
121   1984-02-22
122   1984-03-10
123   1983-03-23
124   1985-03-07
125   1994-01-12
126   1993-06-24
127   1987-05-12
128   1985-04-07
129   1988-02-02
130   1999-06-16
131   1981-08-16
132   1987-12-25
133   1989-02-09
134   1991-09-26
135   1990-01-23
136   1971-04-30
137   1988-02-08
138   1991-09-27
139   1999-12-07
140   1999-11-01
141   1982-08-04
142   1994-09-07
143   1987-04-14
144   1978-01-13
145   1988-03-23
146   1995-09-04
147   1985-11-22
148   1993-07-28
149   1984-05-04
150   1969-08-21
151   1979-12-20
152   1973-03-02
153   1992-02-10
154   1989-12-09
155   1995-09-09
156   1982-02-17
157   1986-09-05
158   1999-08-27
159   1983-01-22
160   1983-08-24
161   1989-09-27
162   1990-09-07
163   1980-03-06
164   1979-02-05
165   1977-02-17
166   1983-04-13
167   1988-03-01
168   1974-04-10
169   1976-08-21
170   1971-06-09
171   1995-09-17
172   1987-07-12
173   1985-05-02
174   1990-07-24
175   1990-03-16
176   1975-02-07
177   1987-10-26
178   1997-09-04
179   1992-08-02
180   1993-08-11
181   2000-04-06
182   1988-05-17
183   1985-09-19
184   1974-01-10
185   1994-04-08
186   1991-04-15
187   1986-08-04
188   1991-10-26
189   1985-12-25
190   1978-08-25
191   1993-12-15
192   1998-01-09
193   1997-06-21
194   1983-11-30
195   1982-05-25
196   1976-12-06
197   1978-09-16
198   1981-08-03
199   1995-07-08
200   1986-04-29
201   1992-09-24
202   1999-01-04
203   1983-04-06
204   1994-06-16
205   1986-01-06
206   1989-01-07
207   1992-08-15
208   1992-12-02
209   1978-05-25
210   1998-02-19
211   1993-01-01
212   1984-03-08
213   1980-08-31
214   1979-05-11
215   1970-11-23
216   1992-02-04
217   1986-11-29
218   1990-07-09
219   1996-05-15
220   1973-03-20
221   1989-12-31
222   1978-04-21
223   1988-06-02
224   1996-01-06
225   1969-03-12
226   1981-06-19
227   1981-11-19
228   1992-09-14
229   1989-03-14
230   1996-03-23
231   1985-11-21
232   1975-09-25
233   1982-03-25
234   1986-02-04
235   1963-01-13
236   1975-11-01
237   1977-01-11
238   1977-04-17
239   1981-03-12
240   1995-07-09
241   1980-04-14
242   1975-05-22
243   1982-04-08
244   1992-08-03
245   1986-03-02
246   1997-06-08
247   1994-11-08
248   1985-01-22
249   1987-09-29
250   1980-12-02
251   1983-12-09
252   1987-12-21
253   1991-10-14
254   1993-07-14
255   1995-07-10
256   1984-05-30
257   1989-03-11
258   1995-07-19
259   1991-07-03
260   1985-10-16
261   1980-01-04
262   1988-12-01
263   1997-06-14
264   1997-06-12
265   1973-07-17
266   1983-07-01
267   1993-03-21
268   1993-10-06
269   1985-07-05
270   1981-10-14
271   1988-08-28
272   1988-09-29
273   1981-04-12
274   1988-11-22
275   1995-03-29
276   1993-11-29
277   1992-08-14
278   1970-05-10
279   1995-12-07
280   1991-12-27
281   1983-09-01
282   1984-09-23
283   1985-09-05
284   1986-08-17
285   1987-04-08
286   1995-01-13
287   1982-09-13
288   1986-05-17
289   1994-06-27
290   1984-09-15
291   1967-10-17
292   1981-09-29
293   1975-02-25
294   1986-06-01
295   1983-08-26
296   1980-09-29
297   1982-02-05
298   1988-09-08
299   1988-03-25
300   1976-10-11
301   1992-12-19
302   1982-07-31
303   1984-12-30
304   1999-03-12
305   1993-12-26
306   1979-04-22
307   1987-03-04
308   1987-02-15
309   1999-01-17
310   1993-06-26
311   1987-05-19
312   1996-05-14
313   1971-03-18
314   1986-01-20
315   1992-12-18
316   1986-09-17
317   1983-11-11
318   1979-06-05
319   1988-05-12
320   1970-10-18
321   1999-06-02
322   1989-04-24
323   1990-12-27
324   1961-09-03
325   1987-12-15
326   1976-10-09
327   1981-12-14
328   1977-11-23
329   1985-08-18
330   1986-04-20
331   1974-07-28
332   1994-10-14
333   1980-09-03
334   1986-07-28
335   1983-07-15
336   1994-07-24
337   1989-11-16
338   1974-04-05
339   1981-10-16
340   1980-09-17
341   1989-01-16
342   1992-01-04
343   1992-07-19
344   1988-12-19
345   1979-09-15
346   1977-02-15
347   1983-01-18
348   1991-07-16
349   1977-03-27
350   1991-05-29
351   1984-08-09
352   1975-06-21
353   1974-06-13
354   1991-11-30
355   1992-12-15
356   1990-12-25
357   1991-09-17
358   1985-06-20
359   1974-01-18
Name: Fecha nacimiento, dtype: datetime64[us]

7)Fecha fin de contrato

In [262]:
df_bajas['Fecha fin de contrato'].head()

0   2019-08-10
1   2019-08-10
2   2019-08-11
3   2019-08-19
4   2019-08-21
Name: Fecha fin de contrato, dtype: datetime64[us]

8) Tipo de baja local

In [263]:
df_bajas['Tipo de baja local'].unique()

<StringArray>
[       'b.2) Otras bajas vegetativas',          'b.1) Renuncias voluntarias',
            'Dispensa Com Justa Causa', 'Dispensa sem Justa Causa AVP Inden.',
           'Falecimento morte natural',                     'Pedido Demissão',
           'Pedido Dem na Experiência',              'Antes Termino Contrato']
Length: 8, dtype: str

In [264]:
analizar_columna(df_bajas,'Tipo de baja local')

                                     Cantidad  Porcentaje (%)
Tipo de baja local
Dispensa sem Justa Causa AVP Inden.       265           73.61
Pedido Demissão                            54           15.00
Dispensa Com Justa Causa                   16            4.44
Pedido Dem na Experiência                  10            2.78
Antes Termino Contrato                      7            1.94
b.1) Renuncias voluntarias                  4            1.11
b.2) Otras bajas vegetativas                2            0.56
Falecimento morte natural                   2            0.56

9)  Clase de empleado

In [265]:
df_bajas['Clase de empleado'].unique()

<StringArray>
['EMP']
Length: 1, dtype: str

10)  Tipo de baja global

In [266]:
df_bajas['Tipo de baja global'].head()

0    b.2) Otras bajas vegetativas
1    b.2) Otras bajas vegetativas
2      b.1) Renuncias voluntarias
3      b.1) Renuncias voluntarias
4      b.1) Renuncias voluntarias
Name: Tipo de baja global, dtype: str

In [267]:
analizar_columna(df_bajas, 'Tipo de baja global' )

                                        Cantidad  Porcentaje (%)
Tipo de baja global
a.2 ) X otras causas (Indemnizaciones)       290           80.56
b.1) Renuncias voluntarias                    68           18.89
b.2) Otras bajas vegetativas                   2            0.56

11) Nombre del puesto

In [268]:
df_bajas['Nombre del puesto'].unique()

<StringArray>
[        'TITULADO SUPERIOR O MASTER',  'TITULADO/TECNICO MEDIO O DE GRADO',
                    'EXPERTO NIVEL 2',                               'STAM',
                       'REPARADOR LA',   'ATENDENTE EXPERIENCIA CLIENTE II',
  'ATENDENTE EXPERIENCIA CLIENTE III',             'ATENDENTE TELEVENDAS I',
         'CONSULTOR NEGOCIOS LOJA 8H',                        'AUXILIAR LA',
 ...
              'GERENTE NEGOCIOS LOJA',                   'ATENDENTE COE PL',
                       'TECNICO ADSL',                       'DIR INSPECAO',
               'ANALISTA PROJETOS SR',       'ATENDENTE RELACIONAMENTO ODC',
           'GERENTE NEGOCIOS LOJA II',   'CONSULTOR INFRAESTRUTURA PREDIAL',
 'ANALISTA PROCESSOS OPERACIONAIS PL',          'ANALISTA GESTAO VENDAS SR']
Length: 111, dtype: str

In [269]:
analizar_columna(df_bajas,'Nombre del puesto')

                                        Cantidad  Porcentaje (%)
Nombre del puesto
ATENDENTE EXPERIENCIA CLIENTE II              45           12.50
ATENDENTE RETENCAO                            22            6.11
CONSULTOR NEGOCIOS LOJA I                     20            5.56
CONSULTOR NEGOCIOS LOJA I 6H                  17            4.72
INSTALADOR LA                                 14            3.89
REPARADOR LA                                  12            3.33
CONSULTOR NEGOCIOS LOJA 8H                    12            3.33
ASSISTENTE TECNICO                            12            3.33
ATENDENTE EXPERIENCIA CLIENTE I                9            2.50
ATENDENTE TELEVENDAS I                         8            2.22
ATENDENTE EXPERIENCIA CLIENTE III              7            1.94
AUXILIAR LA                                    7            1.94
ATENDENTE CO                                   7            1.94
RECEPCIONISTA LOJA                             7            1.94
CONSULTOR RELACIONAMENTO LOJA                  7            1.94
SUPERVISOR SERVICOS AO CLIENTE                 7            1.94
ATENDENTE DE AGENDAMENTO E CONTROLE            6            1.67
CONSULTOR NEGOCIOS LOJA I (NOC)                5            1.39
GERENTE NEGOCIOS II                            4            1.11
TECNICO TELECOM JR                             4            1.11
ASSISTENTE ADMINISTRATIVO                      4            1.11
TITULADO SUPERIOR O MASTER                     3            0.83
ANALISTA TELECOM JR                            3            0.83
CONSULTOR NEGOCIOS PREMIUM                     3            0.83
CONSULTOR SISTEMAS                             3            0.83
GERENTE VENDAS B2C                             3            0.83
CONSULTOR TECNOLOGICO                          3            0.83
GERENTE NEGOCIOS LOJA I                        3            0.83
ANALISTA SUPORTE VENDAS PL                     3            0.83
GERENTE GERAL LOJA II                          3            0.83
ENGENHEIRO TELECOM SR                          2            0.56
GERENTE CONTAS III                             2            0.56
GERENTE GERAL LOJA I                           2            0.56
ANALISTA EXPERIENCIA CLIENTE SR                2            0.56
ANALISTA SUPORTE COMERCIAL I (OC)              2            0.56
GERENTE CONTAS I                               2            0.56
ANALISTA SUPORTE OPERACAO PL                   2            0.56
ATENDENTE TELEVENDAS III                       2            0.56
ATENDENTE RETENCAO VENDAS                      2            0.56
CONSULTOR SUPORTE OPERACAO                     2            0.56
GERENTE NEGOCIOS IS I                          2            0.56
CONSULTOR PRODUCAO TI                          2            0.56
GER SR CONTROLE OPERACOES FIN                  2            0.56
GERENTE NEGOCIOS III                           2            0.56
CONSULTOR MARKETING                            2            0.56
CONSULTOR PROJETOS                             2            0.56
TITULADO/TECNICO MEDIO O DE GRADO              1            0.28
EXPERTO NIVEL 2                                1            0.28
STAM                                           1            0.28
SUPERVISOR ATENDIMENTO OPERACOES               1            0.28
ANALISTA SISTEMAS SR                           1            0.28
GERENTE NEGOCIOS LOJA (ITIN)                   1            0.28
ANALISTA CONTABIL SR                           1            0.28
ANALISTA RELACIONAMENTO COM CLIENTE SR         1            0.28
CONSULTOR CREDITO                              1            0.28
ATENDENTE TELEMARKETING SME                    1            0.28
CONSULTOR GESTÃO DE PESSOAS                    1            0.28
CONSULTOR NEGOCIOS PREMIUM 6H                  1            0.28
ANALISTA GESTAO VENDAS PL                      1            0.28
ANALISTA LOGISTICA PL                          1            0.28
CONSULTOR VENDAS                               1            0.28
ESPECIALISTA PLANEJAMENTO COMERCIAL            1            0.28
ANALISTA PLANEJAMENTO COMERCIAL SR             1            0.28
GERENTE MARKETING                              1            0.28
GERENTE NEGOCIOS V                             1            0.28
COORDENADOR SUPORTE SISTEMAS                   1            0.28
CONSULTOR SUPORTE                              1            0.28
ANALISTA SISTEMAS JR                           1            0.28
GER SR PROCESSOS FINANCEIROS                   1            0.28
CONSULTOR PLANEJAMENTO E CONTROLE              1            0.28
COORDENADOR SERVICO AO CLIENTE                 1            0.28
ANALISTA CONTROLE OPER FINANCEIRAS SR          1            0.28
ANALISTA SERVICO CLIENTE SR                    1            0.28
CONSULTOR BIG DATA                             1            0.28
LIGADOR DG                                     1            0.28
SUPERVISOR SUPORTE VENDAS                      1            0.28
ANALISTA SUPORTE COMERCIAL III                 1            0.28
AUDITOR JR                                     1            0.28
COORDENADOR ADMINISTRATIVO                     1            0.28
ASSISTENTE RELACIONAMENTO ODC                  1            0.28
ANALISTA SUPORTE VENDAS JR                     1            0.28
CONSULTOR TELECOM                              1            0.28
CONSULTOR LOGISTICA                            1            0.28
CONSULTOR PRE VENDAS IV                        1            0.28
ADVOGADO SR                                    1            0.28
SUPERVISOR RETENCAO I                          1            0.28
ANALISTA MARKETING PL                          1            0.28
CONSULTOR CONTABILIDADE                        1            0.28
ANALISTA QUALIDADE OPERACIONAL JR              1            0.28
SUPERVISOR ATENDIMENTO                         1            0.28
ANALISTA SEGURANCA PATRIMONIAL SR              1            0.28
TECNICO TELECOM SR                             1            0.28
SUPERVISOR TELEVENDAS I                        1            0.28
ENGENHEIRO TELECOM PL                          1            0.28
GERENTE RELAC POS VENDAS III                   1            0.28
ANALISTA CANAIS DIGITAIS SR                    1            0.28
TRAINEE                                        1            0.28
ANALISTA PLANEJAMENTO E CONTROLE PL            1            0.28
ANALISTA SUPORTE COMERCIAL I                   1            0.28
ANALISTA MARKETING SR                          1            0.28
GERENTE CONTAS IV                              1            0.28
GERENTE NEGOCIOS LOJA                          1            0.28
ATENDENTE COE PL                               1            0.28
TECNICO ADSL                                   1            0.28
DIR INSPECAO                                   1            0.28
ANALISTA PROJETOS SR                           1            0.28
ATENDENTE RELACIONAMENTO ODC                   1            0.28
GERENTE NEGOCIOS LOJA II                       1            0.28
CONSULTOR INFRAESTRUTURA PREDIAL               1            0.28
ANALISTA PROCESSOS OPERACIONAIS PL             1            0.28
ANALISTA GESTAO VENDAS SR                      1            0.28

# ARCHIVO DF_ALTAS
Se refiere a las altas (contrataciones) que hay en agosto

In [270]:
df_altas.info()

<class 'pandas.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Subactividad_desc       583 non-null    str
 1   Subactividad            583 non-null    str
 2   Genero                  583 non-null    str
 3   Fecha nacimiento        583 non-null    datetime64[us]
 4   Clase empleado          583 non-null    str
 5   Nombre del puesto       583 non-null    str
 6   COD. UNIDAD DE NEGOCIO  583 non-null    int64
 7   Fecha alta              583 non-null    datetime64[us]
 8   Tipo alta local         583 non-null    str
 9   Tipo alta global        583 non-null    str
 10  ID Persona              583 non-null    str
dtypes: datetime64[us](2), int64(1), str(8)
memory usage: 50.2 KB

0 )  Subactividad_desc

In [271]:
df_altas['Subactividad_desc'].unique()

<StringArray>
[                                                     'tecnologíayplanificación',
                                                             'gestionydireccion',
                                                          'vigilanciayseguridad',
                                                                  'contabilidad',
                                                                       'compras',
                                              'gestiónymantenimientodeedificios',
                                                     'planificaciónycontrolling',
                                             'tesoreríayplanificaciónfinanciera',
                                                'administraciónygestióndecobros',
                                       'aseguramientodeingresosycontroldefraude',
                                          'relacioneslaboralesygestióndealiados',
                                       'compensación,beneficiosymovilidadglobal',
                                                              'businesspartners',
                                                                     'formación',
                                                                     'selección',
                                                 'asesoríalegalysoportejurídico',
                                             'relacionesregulatoriasynormativas',
                                                                  'producciónit',
                         'ingenieríayconstruccióndeinfraestructurasderedtroncal',
                        'ingenieríayconstruccióndeinfraestructurasdereddeacceso',
                                                'calidadyoptimizacióndeprocesos',
                                                    'operacionesredparaempresas',
                                                                'operacióndered',
                                                              'supervisióndered',
                                                             'callcentertécnico',
                                                                'logísticadered',
                                           'mantenimientoredtroncal(redinterna)',
                              'instalaciónymantenimientoreddeacceso(redexterna)',
 'marketingdecliente(ofertacomercial,captaciónyfidelización,pricing,terminales)',
                              'desarrollodeproyectosestratégicosytransformación',
                                                      'canaltelefónico-atención',
                                   'logísticadeterminalesyequipamientodecliente',
                                          'planificacióneinteligenciadelnegocio',
                   'marketingdeproducto(diseñoydesarrollodeproductosyservicios)',
                                                           'gestióndecontenidos',
                                                         'fuerzadeventasdirecta',
                                                                 'soporteventas',
                                                                    'backoffice',
                                                       'fuerzadeventasindirecta',
                                                                    'pre-ventas']
Length: 40, dtype: str

In [272]:
analizar_columna(df_altas,'Subactividad_desc')

                                                    Cantidad  Porcentaje (%)
Subactividad_desc
fuerzadeventasdirecta                                    165           28.30
canaltelefónico-atención                                 153           26.24
producciónit                                              98           16.81
callcentertécnico                                         32            5.49
instalaciónymantenimientoreddeacceso(redexterna)          29            4.97
backoffice                                                13            2.23
mantenimientoredtroncal(redinterna)                       11            1.89
operacionesredparaempresas                                 7            1.20
desarrollodeproyectosestratégicosytransformación           7            1.20
soporteventas                                              7            1.20
ingenieríayconstruccióndeinfraestructurasderedt...         5            0.86
tecnologíayplanificación                                   4            0.69
supervisióndered                                           4            0.69
marketingdecliente(ofertacomercial,captaciónyfi...         4            0.69
logísticadeterminalesyequipamientodecliente                4            0.69
tesoreríayplanificaciónfinanciera                          3            0.51
planificacióneinteligenciadelnegocio                       3            0.51
marketingdeproducto(diseñoydesarrollodeproducto...         3            0.51
gestionydireccion                                          2            0.34
contabilidad                                               2            0.34
compras                                                    2            0.34
gestiónymantenimientodeedificios                           2            0.34
planificaciónycontrolling                                  2            0.34
formación                                                  2            0.34
operacióndered                                             2            0.34
fuerzadeventasindirecta                                    2            0.34
pre-ventas                                                 2            0.34
vigilanciayseguridad                                       1            0.17
administraciónygestióndecobros                             1            0.17
aseguramientodeingresosycontroldefraude                    1            0.17
relacioneslaboralesygestióndealiados                       1            0.17
compensación,beneficiosymovilidadglobal                    1            0.17
businesspartners                                           1            0.17
selección                                                  1            0.17
asesoríalegalysoportejurídico                              1            0.17
relacionesregulatoriasynormativas                          1            0.17
ingenieríayconstruccióndeinfraestructurasderedd...         1            0.17
calidadyoptimizacióndeprocesos                             1            0.17
logísticadered                                             1            0.17
gestióndecontenidos                                        1            0.17

 1)  Subactividad

In [273]:
df_altas['Subactividad'].unique()

<StringArray>
[                                                            'Tecnología y Planificación',
                                                                    'Gestión y Direccion',
                                                                 'Vigilancia y Seguridad',
                                                                           'Contabilidad',
                                                                                'Compras',
                                                   'Gestión y mantenimiento de edificios',
                                                            'Planificación y controlling',
                                                   'Tesorería y planificación financiera',
                                                     'Administración y gestión de cobros',
                                          'Aseguramiento de ingresos y control de fraude',
                                              'Relaciones Laborales y Gestión de Aliados',
                                            'Compensación, Beneficios y Movilidad Global',
                                                                      'Business Partners',
                                                                              'Formación',
                                                                              'Selección',
                                                      'Asesoría legal y soporte jurídico',
                                                   'Relaciones regulatorias y normativas',
                                                                          'Producción IT',
                           'Ingeniería y construcción de infraestructuras de Red Troncal',
                         'Ingeniería y construcción de infraestructuras de Red de Acceso',
                                                     'Calidad y Optimización de procesos',
                                                          'Operaciones Red para empresas',
                                                                       'Operación de red',
                                                                     'Supervisión de red',
                                                                    'Call Center técnico',
                                                                       'Logística de red',
                                                'Mantenimiento Red Troncal (Red Interna)',
                                'Instalación y mantenimiento Red de Acceso (Red Externa)',
 'Marketing de Cliente (Oferta Comercial, Captación y fidelización, Pricing, Terminales)',
                                  'Desarrollo de Proyectos Estratégicos y Transformación',
                                                            'Canal telefónico - Atención',
                                      'Logística de terminales y equipamiento de cliente',
                                               'Planificación e Inteligencia del Negocio',
                   'Marketing de Producto (Diseño y desarrollo de productos y servicios)',
                                                                  'Gestión de Contenidos',
                                                               'Fuerza de ventas directa',
                                                                         'Soporte ventas',
                                                                             'Backoffice',
                                                             'Fuerza de ventas indirecta',
                                                                             'Pre-Ventas']
Length: 40, dtype: str

In [274]:
analizar_columna(df_altas,'Subactividad')

                                                    Cantidad  Porcentaje (%)
Subactividad
Fuerza de ventas directa                                 165           28.30
Canal telefónico - Atención                              153           26.24
Producción IT                                             98           16.81
Call Center técnico                                       32            5.49
Instalación y mantenimiento Red de Acceso (Red ...        29            4.97
Backoffice                                                13            2.23
Mantenimiento Red Troncal (Red Interna)                   11            1.89
Operaciones Red para empresas                              7            1.20
Desarrollo de Proyectos Estratégicos y Transfor...         7            1.20
Soporte ventas                                             7            1.20
Ingeniería y construcción de infraestructuras d...         5            0.86
Tecnología y Planificación                                 4            0.69
Supervisión de red                                         4            0.69
Marketing de Cliente (Oferta Comercial, Captaci...         4            0.69
Logística de terminales y equipamiento de cliente          4            0.69
Tesorería y planificación financiera                       3            0.51
Planificación e Inteligencia del Negocio                   3            0.51
Marketing de Producto (Diseño y desarrollo de p...         3            0.51
Gestión y Direccion                                        2            0.34
Contabilidad                                               2            0.34
Compras                                                    2            0.34
Gestión y mantenimiento de edificios                       2            0.34
Planificación y controlling                                2            0.34
Formación                                                  2            0.34
Operación de red                                           2            0.34
Fuerza de ventas indirecta                                 2            0.34
Pre-Ventas                                                 2            0.34
Vigilancia y Seguridad                                     1            0.17
Administración y gestión de cobros                         1            0.17
Aseguramiento de ingresos y control de fraude              1            0.17
Relaciones Laborales y Gestión de Aliados                  1            0.17
Compensación, Beneficios y Movilidad Global                1            0.17
Business Partners                                          1            0.17
Selección                                                  1            0.17
Asesoría legal y soporte jurídico                          1            0.17
Relaciones regulatorias y normativas                       1            0.17
Ingeniería y construcción de infraestructuras d...         1            0.17
Calidad y Optimización de procesos                         1            0.17
Logística de red                                           1            0.17
Gestión de Contenidos                                      1            0.17

2) Genero

In [275]:
analizar_columna(df_altas,'Genero')

        Cantidad  Porcentaje (%)
Genero
M            322           55.23
F            261           44.77

 3) Fecha nacimiento

In [276]:
df_altas['Fecha nacimiento'].head()

0   1966-06-27
1   1970-12-20
2   1971-10-09
3   1971-01-03
4   1962-11-26
Name: Fecha nacimiento, dtype: datetime64[us]

4 ) Clase empleado

In [277]:
df_altas['Clase empleado'].unique()

<StringArray>
['EMP']
Length: 1, dtype: str

5) Nombre del puesto

In [278]:
df_altas['Nombre del puesto'].unique()

<StringArray>
[        'OPERADOR DE COMUNICACIONES',                        'ASESOR BASE',
                     'ADMINISTRATIVO',               'ANALISTA CONTABIL JR',
                       'COMPRADOR SR',      'ANALISTA PROCESSOS COMPRAS JR',
           'CONSULTOR ADMINISTRATIVO',    'CONSULTOR EFICIENCIA DE ENERGIA',
        'ANALISTA COMISSIONAMENTO SR',          'CONSULTOR COMISSIONAMENTO',
 ...
     'CONSULTOR SERVICOS IMPLANTACAO',            'CONSULTOR PRE VENDAS IV',
                 'CONSULTOR PRODUTOS', 'ANALISTA PLANEJAMENTO COMERCIAL JR',
         'ANALISTA SUPORTE VENDAS SR',                'GERENTE NEGOCIOS II',
                 'GERENTE NEGOCIOS V',                'GERENTE NEGOCIOS IV',
               'GERENTE NEGOCIOS III',              'ANALISTA QUALIDADE SR']
Length: 119, dtype: str

In [279]:
analizar_columna(df_altas,'Nombre del puesto')

                                        Cantidad  Porcentaje (%)
Nombre del puesto
ATENDENTE EXPERIENCIA CLIENTE II             114           19.55
CONSULTOR NEGOCIOS LOJA 8H                    68           11.66
CONSULTOR NEGOCIOS LOJA I 6H                  32            5.49
RECEPCIONISTA LOJA                            28            4.80
ATENDENTE CO                                  27            4.63
ANALISTA SISTEMAS SR                          20            3.43
ATENDENTE RETENCAO                            20            3.43
ATENDENTE EXPERIENCIA CLIENTE I               15            2.57
ANALISTA PROJETOS SR                          12            2.06
CONSULTOR NEGOCIOS LOJA I (NOC)               11            1.89
ANALISTA SISTEMAS PL                          10            1.72
CONSULTOR SISTEMAS                            10            1.72
AUXILIAR LA                                    8            1.37
INSTALADOR LA                                  7            1.20
ANALISTA PROJETOS PL                           6            1.03
CONSULTOR PROJETOS                             6            1.03
TECNICO TELECOM JR                             6            1.03
ASSISTENTE TECNICO                             6            1.03
ANALISTA TELECOM JR                            5            0.86
ANALISTA SERVICO CLIENTE JR                    5            0.86
ATENDENTE DE AGENDAMENTO E CONTROLE            5            0.86
ANALISTA SUPORTE COMERCIAL I                   5            0.86
CONSULTOR INOVACAO DIGITAL                     4            0.69
ANALISTA TELECOM SR                            4            0.69
ASSISTENTE ADMINISTRATIVO                      4            0.69
FISCAL TELECOM                                 4            0.69
ANALISTA LOGISTICA JR                          4            0.69
GERENTE CONTAS II                              4            0.69
OPERADOR DE COMUNICACIONES                     3            0.51
ANALISTA QUALIDADE SISTEMAS SR                 3            0.51
ANALISTA SUPORTE SR                            3            0.51
ANALISTA INOVACAO DIGITAL SR                   3            0.51
ANALISTA PROCESSOS JR                          3            0.51
TECNICO TELECOM PL                             3            0.51
ANALISTA MARKETING PL                          3            0.51
ANALISTA SUPORTE VENDAS PL                     3            0.51
ANALISTA SUPORTE VENDAS JR                     3            0.51
CONSULTOR VENDAS                               3            0.51
GERENTE GERAL LOJA I                           3            0.51
GERENTE NEGOCIOS V                             3            0.51
ANALISTA GESTÃO DE PESSOAS PL                  2            0.34
ANALISTA SISTEMAS JR                           2            0.34
CONSULTOR PROCESSOS                            2            0.34
CONSULTOR QUALIDADE SISTEMAS                   2            0.34
ANALISTA PRODUCAO TI JR                        2            0.34
ANALISTA PRODUCAO TI PL                        2            0.34
ANALISTA SUPORTE MICROINFORMATICA SR           2            0.34
ANALISTA INOVACAO DIGITAL PL                   2            0.34
ANALISTA PLANEJAMENTO E CONTROLE JR            2            0.34
ANALISTA TELECOM PL                            2            0.34
ANALISTA SERVICO CLIENTE SR                    2            0.34
ATENDENTE RELACIONAMENTO ODC                   2            0.34
GERENTE CONTAS I                               2            0.34
CONSULTOR TECNOLOGICO                          2            0.34
ANALISTA TRANSFORMACAO DIGITAL SR              2            0.34
CONSULTOR PRE VENDAS IV                        2            0.34
CONSULTOR PRODUTOS                             2            0.34
GERENTE NEGOCIOS II                            2            0.34
ASESOR BASE                                    1            0.17
ADMINISTRATIVO                                 1            0.17
ANALISTA CONTABIL JR                           1            0.17
COMPRADOR SR                                   1            0.17
ANALISTA PROCESSOS COMPRAS JR                  1            0.17
CONSULTOR ADMINISTRATIVO                       1            0.17
CONSULTOR EFICIENCIA DE ENERGIA                1            0.17
ANALISTA COMISSIONAMENTO SR                    1            0.17
CONSULTOR COMISSIONAMENTO                      1            0.17
CONSULTOR TESOURARIA                           1            0.17
ANALISTA TESOURARIA SR                         1            0.17
ANALISTA RISCOS FINANCEIROS SR                 1            0.17
ANALISTA CONTROLE OPER FINANCEIRAS PL          1            0.17
GERENTE SEGURANCA INFORMACAO                   1            0.17
ENGENHEIRO SEGURANCA TRABALHO                  1            0.17
MEDICO DO TRABALHO                             1            0.17
ANALISTA GESTÃO DE PESSOAS SR                  1            0.17
COORDENADOR GESTÃO DE PESSOAS                  1            0.17
CONSULTOR JURIDICO                             1            0.17
ADVOGADO PL                                    1            0.17
GERENTE PROJETOS                               1            0.17
COORDENADOR QUALIDADE SISTEMAS                 1            0.17
ANALISTA SUPORTE SISTEMAS JR                   1            0.17
ANALISTA PRODUCAO TI SR                        1            0.17
ANALISTA SUPORTE PL                            1            0.17
CONSULTOR REDES                                1            0.17
ANALISTA SUPORTE MICROINFORMATICA JR           1            0.17
CONSULTOR TELECOM                              1            0.17
ANALISTA DESENV DE DISPOSITIVOS PL             1            0.17
ANALISTA SERVICO CLIENTE PL                    1            0.17
TECNICO PROJETO PL                             1            0.17
TECNICO CONSTRUCAO REDES JR                    1            0.17
SUPERVISOR REDE                                1            0.17
REPARADOR LA                                   1            0.17
TECNICO SERVICOS DIGITAIS B2B JR               1            0.17
TECNICO SERVICOS DIGITAIS B2B PL               1            0.17
GERENTE CONTAS IV                              1            0.17
ANALISTA MARKETING JR                          1            0.17
CONSULTOR MARKETING                            1            0.17
ANALISTA EXPERIENCIA CLIENTE SR                1            0.17
ANALISTA RELACIONAMENTO COM CLIENTE PL         1            0.17
GERENTE PLANEJAMENTO COMERCIAL                 1            0.17
ANALISTA MARKETING SR                          1            0.17
ATENDENTE SUPORTE VENDAS                       1            0.17
CONSULTOR NEGOCIOS PREMIUM 8H                  1            0.17
ANALISTA TRADE MARKETING PL                    1            0.17
GERENTE NEGOCIOS LOJA                          1            0.17
CONSULTOR CANAIS DIGITAIS                      1            0.17
GERENTE CANAIS DIGITAIS                        1            0.17
ANALISTA SERVICOS IMPLANTACAO SR               1            0.17
CONSULTOR ARQUITETURA SISTEMAS                 1            0.17
ANALISTA ARQUITETURA SISTEMAS PL               1            0.17
GERENTE RELAC POS VENDAS II                    1            0.17
GERENTE RELAC POS VENDAS I                     1            0.17
ANALISTA PROCESSOS PL                          1            0.17
CONSULTOR SERVICOS IMPLANTACAO                 1            0.17
ANALISTA PLANEJAMENTO COMERCIAL JR             1            0.17
ANALISTA SUPORTE VENDAS SR                     1            0.17
GERENTE NEGOCIOS IV                            1            0.17
GERENTE NEGOCIOS III                           1            0.17
ANALISTA QUALIDADE SR                          1            0.17

In [280]:
df_altas['Nombre del puesto'].value_counts().head()

Nombre del puesto
ATENDENTE EXPERIENCIA CLIENTE II    114
CONSULTOR NEGOCIOS LOJA 8H           68
CONSULTOR NEGOCIOS LOJA I 6H         32
RECEPCIONISTA LOJA                   28
ATENDENTE CO                         27
Name: count, dtype: int64

In [281]:
df_altas['Nombre del puesto'].value_counts().tail()

Nombre del puesto
ANALISTA PLANEJAMENTO COMERCIAL JR    1
ANALISTA SUPORTE VENDAS SR            1
GERENTE NEGOCIOS IV                   1
GERENTE NEGOCIOS III                  1
ANALISTA QUALIDADE SR                 1
Name: count, dtype: int64

 6) COD. UNIDAD DE NEGOCIO

In [282]:
df_altas['COD. UNIDAD DE NEGOCIO'].unique()

array([156, 185])

In [283]:
analizar_columna(df_altas,'COD. UNIDAD DE NEGOCIO')

                        Cantidad  Porcentaje (%)
COD. UNIDAD DE NEGOCIO
185                          578           99.14
156                            5            0.86

 7)   Fecha alta

In [284]:
df_altas['Fecha alta'].head()

0   2019-08-28
1   2019-08-09
2   2019-08-04
3   2019-08-13
4   2019-08-08
Name: Fecha alta, dtype: datetime64[us]

8) Tipo alta local

In [285]:
df_altas['Tipo alta local'].unique()

<StringArray>
['c.2) Reincorporaciones', 'Admissão']
Length: 2, dtype: str

In [286]:
analizar_columna(df_altas,'Tipo alta local')

                        Cantidad  Porcentaje (%)
Tipo alta local
Admissão                     578           99.14
c.2) Reincorporaciones         5            0.86

 9) Tipo alta global

In [287]:
df_altas['Tipo alta global'].unique()

<StringArray>
['c.2) Reincorporaciones', 'a) Procedentes de empresas AJENAS AL GRUPO']
Length: 2, dtype: str

In [288]:
analizar_columna(df_altas,'Tipo alta global')

                                            Cantidad  Porcentaje (%)
Tipo alta global
a) Procedentes de empresas AJENAS AL GRUPO       578           99.14
c.2) Reincorporaciones                             5            0.86

 10) ID Persona

In [289]:
df_altas['ID Persona'].head()

0    Persona 19887
1    Persona 19888
2    Persona 19890
3    Persona 19891
4    Persona 19892
Name: ID Persona, dtype: str

In [290]:
df_julio.isna().sum()

Convenio Aplicable                                   24631
Localización País                                        0
Área Funcional                                       32436
Localización Ciudad                                      0
Subactividad_desc                                        0
Año                                                      0
COD. UNIDAD DE NEGOCIO                                   0
Mes                                                      0
Reducción de Jormada                                     0
Tipo de contrato                                         0
División                                                 0
Subactividad                                             0
Género                                                   0
Departamento                                           445
HORAS TEÓRICAS SEMANALES POR UNIDAD DE NEGOCIO           0
Nombre del puesto                                        0
Nacionalidad                                         32412
Estado de empleado                                       0
PROMEDIO DE HORAS  SEMANALES TRABAJADAS EN EL MES        0
Fecha de Nacimiento                                      0
Clase de empleado                                        0
Discapacidad                                             0
Fecha de Alta                                            0
ID persona                                               0
dtype: int64

In [291]:
df_julio.duplicated().sum()

np.int64(0)

In [292]:
df_altas.isna().sum()

Subactividad_desc         0
Subactividad              0
Genero                    0
Fecha nacimiento          0
Clase empleado            0
Nombre del puesto         0
COD. UNIDAD DE NEGOCIO    0
Fecha alta                0
Tipo alta local           0
Tipo alta global          0
ID Persona                0
dtype: int64

In [293]:
df_altas.duplicated().sum()

np.int64(0)

In [294]:
df_bajas.isna().sum()

ID persona                0
Unidad de Negocio         0
COD. UNIDAD DE NEGOCIO    0
Subactividad_desc         0
Subactividad              0
Genero                    0
Fecha nacimiento          0
Fecha fin de contrato     0
Tipo de baja local        0
Clase de empleado         0
Tipo de baja global       0
Nombre del puesto         0
dtype: int64

In [295]:
df_bajas.duplicated().sum()

np.int64(0)